export interface CityInfo {
  name: string;
  longitude: number; // degrees East
}

export interface ProvinceInfo {
  name: string;
  cities: CityInfo[];
}

export const PROVINCES: ProvinceInfo[] = [
  // ─── 直轄市 ───────────────────────────────────────────
  {
    name: '北京市',
    cities: [{ name: '北京', longitude: 116.4 }],
  },
  {
    name: '天津市',
    cities: [{ name: '天津', longitude: 117.2 }],
  },
  {
    name: '上海市',
    cities: [{ name: '上海', longitude: 121.5 }],
  },
  {
    name: '重慶市',
    cities: [
      { name: '重慶', longitude: 106.6 },
      { name: '萬州', longitude: 108.4 },
      { name: '涪陵', longitude: 107.4 },
      { name: '黔江', longitude: 108.8 },
    ],
  },

  // ─── 華北 ─────────────────────────────────────────────
  {
    name: '河北省',
    cities: [
      { name: '石家莊', longitude: 114.5 },
      { name: '保定', longitude: 115.5 },
      { name: '唐山', longitude: 118.2 },
      { name: '秦皇島', longitude: 119.6 },
      { name: '廊坊', longitude: 116.7 },
      { name: '張家口', longitude: 114.9 },
      { name: '承德', longitude: 117.9 },
      { name: '滄州', longitude: 116.8 },
      { name: '邯鄲', longitude: 114.5 },
      { name: '衡水', longitude: 115.7 },
      { name: '邢臺', longitude: 114.5 },
    ],
  },
  {
    name: '山西省',
    cities: [
      { name: '太原', longitude: 112.6 },
      { name: '大同', longitude: 113.3 },
      { name: '長治', longitude: 113.1 },
      { name: '晉城', longitude: 112.9 },
      { name: '朔州', longitude: 112.4 },
      { name: '晉中', longitude: 112.8 },
      { name: '運城', longitude: 111.0 },
      { name: '忻州', longitude: 112.7 },
      { name: '臨汾', longitude: 111.5 },
      { name: '呂梁', longitude: 111.1 },
    ],
  },
  {
    name: '內蒙古自治區',
    cities: [
      { name: '呼和浩特', longitude: 111.7 },
      { name: '包頭', longitude: 110.0 },
      { name: '鄂爾多斯', longitude: 109.8 },
      { name: '赤峰', longitude: 118.9 },
      { name: '通遼', longitude: 122.3 },
      { name: '呼倫貝爾', longitude: 119.7 },
      { name: '烏蘭察布', longitude: 113.1 },
      { name: '巴彥淖爾', longitude: 107.4 },
      { name: '錫林郭勒', longitude: 116.1 },
    ],
  },

  // ─── 東北 ─────────────────────────────────────────────
  {
    name: '遼寧省',
    cities: [
      { name: '瀋陽', longitude: 123.4 },
      { name: '大連', longitude: 121.6 },
      { name: '鞍山', longitude: 122.9 },
      { name: '撫順', longitude: 123.9 },
      { name: '本溪', longitude: 123.8 },
      { name: '丹東', longitude: 124.4 },
      { name: '錦州', longitude: 121.1 },
      { name: '營口', longitude: 122.2 },
      { name: '阜新', longitude: 121.7 },
      { name: '遼陽', longitude: 123.2 },
      { name: '朝陽', longitude: 120.5 },
      { name: '盤錦', longitude: 122.1 },
      { name: '葫蘆島', longitude: 120.8 },
    ],
  },
  {
    name: '吉林省',
    cities: [
      { name: '長春', longitude: 125.4 },
      { name: '吉林', longitude: 126.6 },
      { name: '四平', longitude: 124.4 },
      { name: '遼源', longitude: 125.1 },
      { name: '通化', longitude: 125.9 },
      { name: '白山', longitude: 126.4 },
      { name: '松原', longitude: 124.8 },
      { name: '白城', longitude: 122.8 },
      { name: '延邊', longitude: 129.5 },
    ],
  },
  {
    name: '黑龍江省',
    cities: [
      { name: '哈爾濱', longitude: 126.5 },
      { name: '齊齊哈爾', longitude: 123.9 },
      { name: '牡丹江', longitude: 129.6 },
      { name: '佳木斯', longitude: 130.4 },
      { name: '大慶', longitude: 125.0 },
      { name: '綏化', longitude: 126.9 },
      { name: '雞西', longitude: 130.9 },
      { name: '雙鴨山', longitude: 131.2 },
      { name: '伊春', longitude: 128.9 },
      { name: '七臺河', longitude: 130.8 },
      { name: '鶴崗', longitude: 130.3 },
      { name: '黑河', longitude: 127.5 },
    ],
  },

  // ─── 華東 ─────────────────────────────────────────────
  {
    name: '江蘇省',
    cities: [
      { name: '南京', longitude: 118.8 },
      { name: '蘇州', longitude: 120.6 },
      { name: '無錫', longitude: 120.3 },
      { name: '常州', longitude: 119.9 },
      { name: '南通', longitude: 120.9 },
      { name: '揚州', longitude: 119.4 },
      { name: '徐州', longitude: 117.2 },
      { name: '連雲港', longitude: 119.2 },
      { name: '淮安', longitude: 119.0 },
      { name: '鹽城', longitude: 120.2 },
      { name: '鎮江', longitude: 119.5 },
      { name: '泰州', longitude: 119.9 },
      { name: '宿遷', longitude: 118.3 },
    ],
  },
  {
    name: '浙江省',
    cities: [
      { name: '杭州', longitude: 120.1 },
      { name: '寧波', longitude: 121.6 },
      { name: '溫州', longitude: 120.7 },
      { name: '嘉興', longitude: 120.8 },
      { name: '湖州', longitude: 120.1 },
      { name: '紹興', longitude: 120.6 },
      { name: '金華', longitude: 119.6 },
      { name: '衢州', longitude: 118.9 },
      { name: '舟山', longitude: 122.1 },
      { name: '台州', longitude: 121.4 },
      { name: '麗水', longitude: 119.9 },
    ],
  },
  {
    name: '安徽省',
    cities: [
      { name: '合肥', longitude: 117.3 },
      { name: '蕪湖', longitude: 118.4 },
      { name: '蚌埠', longitude: 117.4 },
      { name: '淮南', longitude: 117.0 },
      { name: '馬鞍山', longitude: 118.5 },
      { name: '淮北', longitude: 116.8 },
      { name: '銅陵', longitude: 117.8 },
      { name: '安慶', longitude: 117.1 },
      { name: '黃山', longitude: 118.3 },
      { name: '滁州', longitude: 118.3 },
      { name: '阜陽', longitude: 115.8 },
      { name: '宿州', longitude: 116.9 },
      { name: '六安', longitude: 116.5 },
      { name: '亳州', longitude: 115.8 },
    ],
  },
  {
    name: '福建省',
    cities: [
      { name: '福州', longitude: 119.3 },
      { name: '廈門', longitude: 118.1 },
      { name: '莆田', longitude: 119.0 },
      { name: '三明', longitude: 117.6 },
      { name: '泉州', longitude: 118.7 },
      { name: '漳州', longitude: 117.6 },
      { name: '南平', longitude: 118.2 },
      { name: '龍巖', longitude: 117.0 },
      { name: '寧德', longitude: 119.5 },
    ],
  },
  {
    name: '江西省',
    cities: [
      { name: '南昌', longitude: 115.9 },
      { name: '景德鎮', longitude: 117.2 },
      { name: '萍鄉', longitude: 113.9 },
      { name: '九江', longitude: 116.0 },
      { name: '新餘', longitude: 114.9 },
      { name: '鷹潭', longitude: 117.1 },
      { name: '贛州', longitude: 114.9 },
      { name: '吉安', longitude: 114.9 },
      { name: '宜春', longitude: 114.4 },
      { name: '撫州', longitude: 116.4 },
      { name: '上饒', longitude: 117.9 },
    ],
  },
  {
    name: '山東省',
    cities: [
      { name: '濟南', longitude: 117.0 },
      { name: '青島', longitude: 120.4 },
      { name: '淄博', longitude: 118.1 },
      { name: '棗莊', longitude: 117.6 },
      { name: '東營', longitude: 118.7 },
      { name: '煙臺', longitude: 121.4 },
      { name: '濰坊', longitude: 119.1 },
      { name: '濟寧', longitude: 116.6 },
      { name: '泰安', longitude: 117.1 },
      { name: '威海', longitude: 122.1 },
      { name: '日照', longitude: 119.5 },
      { name: '臨沂', longitude: 118.4 },
      { name: '德州', longitude: 116.4 },
      { name: '聊城', longitude: 116.0 },
      { name: '濱州', longitude: 118.0 },
      { name: '菏澤', longitude: 115.5 },
    ],
  },

  // ─── 華中 ─────────────────────────────────────────────
  {
    name: '河南省',
    cities: [
      { name: '鄭州', longitude: 113.6 },
      { name: '開封', longitude: 114.3 },
      { name: '洛陽', longitude: 112.5 },
      { name: '平頂山', longitude: 113.3 },
      { name: '安陽', longitude: 114.4 },
      { name: '鶴壁', longitude: 114.3 },
      { name: '新鄉', longitude: 113.9 },
      { name: '焦作', longitude: 113.2 },
      { name: '濮陽', longitude: 115.0 },
      { name: '許昌', longitude: 113.8 },
      { name: '漯河', longitude: 114.0 },
      { name: '三門峽', longitude: 111.2 },
      { name: '南陽', longitude: 112.5 },
      { name: '商丘', longitude: 115.6 },
      { name: '信陽', longitude: 114.1 },
      { name: '周口', longitude: 114.7 },
      { name: '駐馬店', longitude: 114.0 },
    ],
  },
  {
    name: '湖北省',
    cities: [
      { name: '武漢', longitude: 114.3 },
      { name: '黃石', longitude: 115.0 },
      { name: '十堰', longitude: 110.8 },
      { name: '宜昌', longitude: 111.3 },
      { name: '襄陽', longitude: 112.1 },
      { name: '鄂州', longitude: 114.9 },
      { name: '荊門', longitude: 112.2 },
      { name: '孝感', longitude: 113.9 },
      { name: '荊州', longitude: 112.2 },
      { name: '黃岡', longitude: 114.9 },
      { name: '咸寧', longitude: 114.3 },
      { name: '隨州', longitude: 113.4 },
      { name: '恩施', longitude: 109.5 },
    ],
  },
  {
    name: '湖南省',
    cities: [
      { name: '長沙', longitude: 113.0 },
      { name: '株洲', longitude: 113.1 },
      { name: '湘潭', longitude: 112.9 },
      { name: '衡陽', longitude: 112.6 },
      { name: '邵陽', longitude: 111.5 },
      { name: '岳陽', longitude: 113.1 },
      { name: '常德', longitude: 111.7 },
      { name: '張家界', longitude: 110.5 },
      { name: '益陽', longitude: 112.4 },
      { name: '郴州', longitude: 113.0 },
      { name: '永州', longitude: 111.6 },
      { name: '懷化', longitude: 110.0 },
      { name: '婁底', longitude: 112.0 },
      { name: '湘西', longitude: 109.7 },
    ],
  },

  // ─── 華南 ─────────────────────────────────────────────
  {
    name: '廣東省',
    cities: [
      { name: '廣州', longitude: 113.3 },
      { name: '深圳', longitude: 114.1 },
      { name: '珠海', longitude: 113.6 },
      { name: '佛山', longitude: 113.1 },
      { name: '東莞', longitude: 113.8 },
      { name: '中山', longitude: 113.4 },
      { name: '江門', longitude: 113.1 },
      { name: '惠州', longitude: 114.4 },
      { name: '汕頭', longitude: 116.7 },
      { name: '湛江', longitude: 110.4 },
      { name: '茂名', longitude: 110.9 },
      { name: '肇慶', longitude: 112.5 },
      { name: '梅州', longitude: 116.1 },
      { name: '韶關', longitude: 113.6 },
      { name: '陽江', longitude: 111.9 },
      { name: '清遠', longitude: 113.1 },
      { name: '潮州', longitude: 116.6 },
      { name: '揭陽', longitude: 116.4 },
      { name: '雲浮', longitude: 112.0 },
    ],
  },
  {
    name: '廣西壯族自治區',
    cities: [
      { name: '南寧', longitude: 108.3 },
      { name: '柳州', longitude: 109.4 },
      { name: '桂林', longitude: 110.3 },
      { name: '梧州', longitude: 111.3 },
      { name: '北海', longitude: 109.1 },
      { name: '防城港', longitude: 108.4 },
      { name: '欽州', longitude: 108.6 },
      { name: '貴港', longitude: 109.6 },
      { name: '玉林', longitude: 110.2 },
      { name: '百色', longitude: 106.6 },
      { name: '賀州', longitude: 111.6 },
      { name: '河池', longitude: 108.1 },
      { name: '來賓', longitude: 109.2 },
      { name: '崇左', longitude: 107.4 },
    ],
  },
  {
    name: '海南省',
    cities: [
      { name: '海口', longitude: 110.3 },
      { name: '三亞', longitude: 109.5 },
      { name: '儋州', longitude: 109.6 },
      { name: '文昌', longitude: 110.8 },
      { name: '瓊海', longitude: 110.5 },
      { name: '萬寧', longitude: 110.4 },
      { name: '陵水', longitude: 110.0 },
      { name: '樂東', longitude: 109.2 },
      { name: '五指山', longitude: 109.5 },
    ],
  },

  // ─── 西南 ─────────────────────────────────────────────
  {
    name: '四川省',
    cities: [
      { name: '成都', longitude: 104.1 },
      { name: '綿陽', longitude: 104.7 },
      { name: '德陽', longitude: 104.4 },
      { name: '宜賓', longitude: 104.6 },
      { name: '瀘州', longitude: 105.4 },
      { name: '達州', longitude: 107.5 },
      { name: '南充', longitude: 106.1 },
      { name: '樂山', longitude: 103.8 },
      { name: '自貢', longitude: 104.8 },
      { name: '攀枝花', longitude: 101.7 },
      { name: '遂寧', longitude: 105.6 },
      { name: '內江', longitude: 105.1 },
      { name: '廣元', longitude: 105.8 },
      { name: '雅安', longitude: 103.0 },
      { name: '巴中', longitude: 106.8 },
      { name: '資陽', longitude: 104.6 },
      { name: '廣安', longitude: 106.6 },
      { name: '眉山', longitude: 103.8 },
      { name: '涼山', longitude: 102.3 },
      { name: '甘孜', longitude: 101.9 },
      { name: '阿壩', longitude: 102.2 },
    ],
  },
  {
    name: '貴州省',
    cities: [
      { name: '貴陽', longitude: 106.7 },
      { name: '遵義', longitude: 106.9 },
      { name: '六盤水', longitude: 104.8 },
      { name: '安順', longitude: 105.9 },
      { name: '畢節', longitude: 105.3 },
      { name: '銅仁', longitude: 109.2 },
      { name: '黔西南', longitude: 104.9 },
      { name: '黔東南', longitude: 107.9 },
      { name: '黔南', longitude: 107.5 },
    ],
  },
  {
    name: '雲南省',
    cities: [
      { name: '昆明', longitude: 102.7 },
      { name: '曲靖', longitude: 103.8 },
      { name: '玉溪', longitude: 102.5 },
      { name: '保山', longitude: 99.2 },
      { name: '昭通', longitude: 103.7 },
      { name: '麗江', longitude: 100.2 },
      { name: '普洱', longitude: 101.0 },
      { name: '臨滄', longitude: 100.1 },
      { name: '楚雄', longitude: 101.5 },
      { name: '紅河', longitude: 103.5 },
      { name: '文山', longitude: 104.2 },
      { name: '西雙版納', longitude: 100.8 },
      { name: '大理', longitude: 100.2 },
      { name: '德宏', longitude: 98.6 },
      { name: '怒江', longitude: 98.8 },
      { name: '迪慶', longitude: 99.7 },
    ],
  },
  {
    name: '西藏自治區',
    cities: [
      { name: '拉薩', longitude: 91.1 },
      { name: '日喀則', longitude: 88.9 },
      { name: '昌都', longitude: 97.2 },
      { name: '林芝', longitude: 94.4 },
      { name: '山南', longitude: 91.8 },
      { name: '那曲', longitude: 92.1 },
      { name: '阿里', longitude: 80.1 },
    ],
  },

  // ─── 西北 ─────────────────────────────────────────────
  {
    name: '陝西省',
    cities: [
      { name: '西安', longitude: 108.9 },
      { name: '咸陽', longitude: 108.7 },
      { name: '寶雞', longitude: 107.2 },
      { name: '銅川', longitude: 109.1 },
      { name: '渭南', longitude: 109.5 },
      { name: '延安', longitude: 109.5 },
      { name: '漢中', longitude: 107.1 },
      { name: '榆林', longitude: 109.7 },
      { name: '安康', longitude: 109.0 },
      { name: '商洛', longitude: 109.9 },
    ],
  },
  {
    name: '甘肅省',
    cities: [
      { name: '蘭州', longitude: 103.8 },
      { name: '嘉峪關', longitude: 98.3 },
      { name: '金昌', longitude: 102.2 },
      { name: '白銀', longitude: 104.2 },
      { name: '天水', longitude: 105.7 },
      { name: '武威', longitude: 102.6 },
      { name: '張掖', longitude: 100.5 },
      { name: '平涼', longitude: 106.7 },
      { name: '酒泉', longitude: 98.5 },
      { name: '慶陽', longitude: 107.6 },
      { name: '定西', longitude: 104.6 },
      { name: '隴南', longitude: 104.9 },
      { name: '臨夏', longitude: 103.2 },
      { name: '甘南', longitude: 102.9 },
    ],
  },
  {
    name: '青海省',
    cities: [
      { name: '西寧', longitude: 101.8 },
      { name: '海東', longitude: 102.1 },
      { name: '格爾木', longitude: 94.9 },
      { name: '德令哈', longitude: 97.4 },
      { name: '玉樹', longitude: 97.0 },
      { name: '果洛', longitude: 100.2 },
      { name: '海西', longitude: 97.4 },
    ],
  },
  {
    name: '寧夏回族自治區',
    cities: [
      { name: '銀川', longitude: 106.3 },
      { name: '石嘴山', longitude: 106.4 },
      { name: '吳忠', longitude: 106.2 },
      { name: '固原', longitude: 106.3 },
      { name: '中衛', longitude: 105.2 },
    ],
  },
  {
    name: '新疆維吾爾自治區',
    cities: [
      { name: '烏魯木齊', longitude: 87.6 },
      { name: '克拉瑪依', longitude: 84.9 },
      { name: '吐魯番', longitude: 89.2 },
      { name: '哈密', longitude: 93.5 },
      { name: '昌吉', longitude: 87.3 },
      { name: '博爾塔拉', longitude: 82.1 },
      { name: '巴音郭楞', longitude: 86.2 },
      { name: '阿克蘇', longitude: 80.3 },
      { name: '克孜勒蘇', longitude: 76.2 },
      { name: '喀什', longitude: 75.9 },
      { name: '和田', longitude: 79.9 },
      { name: '伊犁', longitude: 81.3 },
      { name: '塔城', longitude: 83.0 },
      { name: '阿勒泰', longitude: 88.1 },
      { name: '石河子', longitude: 86.1 },
    ],
  },
];
