/**
 * 人紀 — 倪海廈中醫經典教學體系資料庫
 *
 * 「中知人事」—— 人之紀，是中醫經典的體系化教學。
 * 2004-2005年完成，包含五大中醫經典課程。
 * 學習順序：針灸 → 黃帝內經 → 神農本草經 → 傷寒論 → 金匱要略
 *
 * 核心理念：
 *   中醫是物理醫學，從物理的角度分析人的身體。
 *   學成者可從感冒治療至肝癌。
 */

import type { NiModule, AcuExperience, TransNeedling, HantangFormula, ClassicFormula } from './types';

// ─── 人紀模組 ────────────────────────────────────────────
export const RENJI_MODULES: NiModule[] = [
  {
    id: 'rj-zhenjiu',
    category: 'renji',
    name: '針灸大成',
    nameEn: 'Zhen Jiu Da Cheng',
    subtitle: '人紀第一課 · 經絡穴位',
    description: '針灸是人紀的入門課程，依據《針灸甲乙經》和《針灸大成》講授。透過經絡穴位的學習，建立對人體氣血執行的基本認知。',
    details: [
      '針灸課是人紀系列的第一門課，也是中醫入門的基礎。倪師強調，不懂經絡穴位就無法理解中醫的診斷與治療。',
      '課程依據《針灸甲乙經》和《針灸大成》兩部經典編寫，系統講解十二正經、奇經八脈的循行路線與主要穴位。',
      '倪師的針灸教學注重實戰，每個穴位都有具體的臨床應用說明，而非純粹的理論記憶。',
      '倪師認為針灸是「最快速的治療手段」，許多急症可以透過針灸迅速緩解。',
    ],
    lessons: '44集（每集約44分鐘）',
    references: [
      '《針灸甲乙經》',
      '《針灸大成》',
      '倪海廈《人紀·針灸》講義',
    ],
    keywords: ['針灸', '經絡', '穴位', '十二正經', '奇經八脈', '針灸大成', '針灸甲乙經'],
    icon: '⊕',
    status: 'active',
    order: 1,
    slug: 'zhenjiu',
    chapters: [
      {
        id: 'rj-zj-01',
        title: '經絡總論',
        subtitle: '十二正經與奇經八脈',
        description: '人體經絡系統的整體框架，十二正經的循行路線與奇經八脈的特殊功能。',
        keyPoints: [
          '十二正經：手三陰、手三陽、足三陰、足三陽',
          '奇經八脈：任、督、衝、帶、陰維、陽維、陰蹺、陽蹺',
          '經絡的氣血流注時間（子午流注）',
          '經絡與臟腑的表裡關係',
        ],
        order: 1,
      },
      {
        id: 'rj-zj-02',
        title: '重要穴位詳解',
        subtitle: '臨床常用穴位與配伍',
        description: '臨床最常用的穴位定位、取穴方法與針刺技巧，以及常見病症的穴位配伍。',
        keyPoints: [
          '五輸穴（井滎輸經合）的運用',
          '原穴、絡穴、俞穴、募穴的區別',
          '特殊穴位：百會、合谷、足三里、三陰交等',
          '補瀉手法：提插補瀉、捻轉補瀉',
        ],
        order: 2,
      },
      {
        id: 'rj-zj-03',
        title: '針灸治療實戰',
        subtitle: '常見病症的針灸方案',
        description: '從頭痛到腰痛，從感冒到失眠，覆蓋常見病症的針灸治療方案。',
        keyPoints: [
          '頭痛：不同經絡的頭痛對應不同穴位',
          '腰痛：委中、腎俞、大腸俞的運用',
          '急症：中風急救的針灸方法',
          '內科：失眠、消化不良、月經不調等',
        ],
        order: 3,
      },
    ],
  },
  {
    id: 'rj-neijing',
    category: 'renji',
    name: '黃帝內經',
    nameEn: 'Huang Di Nei Jing',
    subtitle: '人紀第二課 · 中醫理論根基',
    description: '《黃帝內經》是中醫的理論根基，倪師透過講解《素問》和《靈樞》，建立完整的中醫哲學與診斷體系。',
    details: [
      '《黃帝內經》分為《素問》和《靈樞》兩部分，是中醫理論的最高經典。',
      '倪師的講解不是逐字翻譯，而是將古文智慧轉化為可操作的臨床知識。',
      '核心內容包括陰陽五行理論、臟腑學說、病因病機、診斷方法等。',
      '倪師特別強調「形神合一」的概念——中醫不僅治病，更關注整體生命狀態。',
    ],
    lessons: '20集（每集約1小時）',
    references: [
      '《黃帝內經·素問》',
      '《黃帝內經·靈樞》',
      '倪海廈《人紀·黃帝內經》講義',
    ],
    keywords: ['黃帝內經', '素問', '靈樞', '陰陽', '五行', '臟腑', '病因病機', '形神'],
    icon: '☯',
    status: 'active',
    order: 2,
    slug: 'neijing',
    chapters: [
      {
        id: 'rj-nj-01',
        title: '陰陽五行',
        subtitle: '中醫哲學基礎',
        description: '陰陽對立統一與五行生剋制化的基本理論，是理解中醫一切診斷治療的基礎。',
        keyPoints: [
          '陰陽的基本特徵與相互關係',
          '五行（木火土金水）的生克關係',
          '五行與臟腑的對應：肝木、心火、脾土、肺金、腎水',
          '五行在診斷和治療中的應用',
        ],
        order: 1,
      },
      {
        id: 'rj-nj-02',
        title: '臟腑學說',
        subtitle: '五臟六腑的功能與關係',
        description: '五臟（肝心脾肺腎）和六腑（膽小腸胃大腸膀胱三焦）的生理功能與相互關係。',
        keyPoints: [
          '五臟藏精氣、六腑傳化水谷',
          '臟腑表裡關係：肝膽、心小腸、脾胃等',
          '氣血津液的生成與執行',
          '臟腑失調的病理表現',
        ],
        order: 2,
      },
      {
        id: 'rj-nj-03',
        title: '診斷方法',
        subtitle: '望聞問切四診',
        description: '中醫四診——望（觀察）、聞（聽聞）、問（詢問）、切（脈診）的具體方法。',
        keyPoints: [
          '望診：面色、舌象、形體、神態',
          '聞診：聲音、氣味的辨別',
          '問診：寒熱、汗、疼痛、二便等',
          '切診：脈象的基本分類與診斷意義',
        ],
        order: 3,
      },
    ],
  },
  {
    id: 'rj-bencao',
    category: 'renji',
    name: '神農本草經',
    nameEn: 'Shen Nong Ben Cao Jing',
    subtitle: '人紀第三課 · 藥物學根基',
    description: '《神農本草經》是中藥學的鼻祖，倪師按上中下三品分類講解365味藥物的性味歸經與臨床運用。',
    details: [
      '《神農本草經》將藥物分為上品（養命）、中品（養性）、下品（治病）三類。',
      '倪師的講解重點在於每味藥的核心功效和臨床實際運用，而非死記硬背。',
      '課程特別強調「藥有真假」——如何辨別藥材的真偽和質量。',
      '倪師認為掌握本草經是開方用藥的根基，沒有這個基礎，傷寒論和金匱的方劑就無法靈活運用。',
    ],
    lessons: '46集（每集約1小時）',
    references: [
      '《神農本草經》',
      '倪海廈《人紀·神農本草經》講義',
    ],
    keywords: ['神農本草經', '中藥', '本草', '上品', '中品', '下品', '性味歸經', '藥性'],
    icon: '⚘',
    status: 'active',
    order: 3,
    slug: 'bencao',
    chapters: [
      {
        id: 'rj-bc-01',
        title: '上品藥物',
        subtitle: '養命延年 · 無毒',
        description: '上品120味，主養命以應天，無毒，多服久服不傷人。',
        keyPoints: [
          '人參：大補元氣，生津止渴',
          '黃芪：補氣固表，利水消腫',
          '甘草：調和諸藥，補中益氣',
          '上品藥可作為日常調養之用',
        ],
        order: 1,
      },
      {
        id: 'rj-bc-02',
        title: '中品藥物',
        subtitle: '養性補虛 · 有毒無毒',
        description: '中品120味，主養性以應人，無毒有毒，斟酌其宜。',
        keyPoints: [
          '當歸：補血活血，調經止痛',
          '黃芩：清熱燥溼，瀉火解毒',
          '白朮：健脾益氣，燥溼利水',
          '中品藥需要根據病情斟酌使用',
        ],
        order: 2,
      },
      {
        id: 'rj-bc-03',
        title: '下品藥物',
        subtitle: '治病祛邪 · 有毒',
        description: '下品125味，主治病以應地，多毒不可久服。',
        keyPoints: [
          '附子：回陽救逆，大熱',
          '大黃：瀉下攻積，清熱瀉火',
          '巴豆：峻下冷積，有大毒',
          '下品藥針對性強，需謹慎使用',
        ],
        order: 3,
      },
    ],
  },
  {
    id: 'rj-shanghan',
    category: 'renji',
    name: '傷寒論',
    nameEn: 'Shang Han Lun',
    subtitle: '人紀第四課 · 辨證論治典範',
    description: '張仲景《傷寒論》是中醫辨證論治的典範之作，倪師逐條講解六經辨證體系與經方運用。',
    details: [
      '《傷寒論》以六經（太陽、陽明、少陽、太陰、少陰、厥陰）辨證為綱，系統闡述外感病的診治。',
      '倪師的講解注重臨床實用性，每一條文都結合實際病例說明。',
      '經方（張仲景的方劑）是中醫臨床的核心武器，倪師強調「經方一劑知，二劑已」的神效。',
      '倪師認為傷寒論不僅治外感，更是治療一切疾病的方法論基礎。',
    ],
    lessons: '傷寒論原版DVD（每集約2小時）',
    references: [
      '《傷寒論》（張仲景）',
      '倪海廈《人紀·傷寒論》講義',
    ],
    keywords: ['傷寒論', '張仲景', '六經辨證', '經方', '太陽病', '陽明病', '少陽病', '桂枝湯', '麻黃湯'],
    icon: '⚕',
    status: 'active',
    order: 4,
    slug: 'shanghan',
    chapters: [
      {
        id: 'rj-sh-01',
        title: '六經辨證總論',
        subtitle: '太陽陽明少陽太陰少陰厥陰',
        description: '六經辨證是傷寒論的核心框架，將一切外感病按六經歸類，指導治療方向。',
        keyPoints: [
          '太陽病：惡寒發熱，頭痛項強——表證',
          '陽明病：壯熱汗出，大渴大煩——裡實熱證',
          '少陽病：往來寒熱，胸脅苦滿——半表半里',
          '太陰病：腹滿而吐，食不下——裡虛寒證',
          '少陰病：脈微細，但欲寐——陽虛寒化或陰虛熱化',
          '厥陰病：消渴，氣上撞心——寒熱錯雜',
        ],
        order: 1,
      },
      {
        id: 'rj-sh-02',
        title: '核心經方',
        subtitle: '桂枝湯、麻黃湯等經典方劑',
        description: '傷寒論中最重要的方劑，每一首方都有明確的適應症和使用條件。',
        keyPoints: [
          '桂枝湯：調和營衛，太陽中風第一方',
          '麻黃湯：發汗解表，太陽傷寒第一方',
          '小柴胡湯：和解少陽，柴胡證的主方',
          '白虎湯：清陽明裡熱',
          '四逆湯：回陽救逆，少陰寒化的主方',
        ],
        order: 2,
      },
      {
        id: 'rj-sh-03',
        title: '方證辨析',
        subtitle: '同病異治與異病同治',
        description: '透過傷寒論的條文學習辨證論治的精髓——同一疾病可用不同方劑，不同疾病可用同一方劑。',
        keyPoints: [
          '辨證而非辨病：看的是證型而非病名',
          '方證對應：每個方劑有其特定的適應症候群',
          '經方加減：根據兼證靈活加減',
          '傳經與變證的判斷',
        ],
        order: 3,
      },
    ],
  },
  {
    id: 'rj-jingui',
    category: 'renji',
    name: '金匱要略',
    nameEn: 'Jin Gui Yao Lue',
    subtitle: '人紀第五課 · 雜病診治大成',
    description: '張仲景《金匱要略》是中醫雜病治療的最高經典，倪師講解各種內科雜病的辨證論治方法。',
    details: [
      '《金匱要略》是《傷寒雜病論》的雜病部分，與《傷寒論》互為補充。',
      '傷寒論主治外感，金匱主治內傷雜病——兩者合起來就是張仲景的完整臨床體系。',
      '倪師的講解涵蓋痰飲、水氣、黃疸、婦人病等各類雜病的診治。',
      '金匱是人紀最後一門課，需要前四門課的知識基礎才能理解運用。',
    ],
    lessons: '20集（每集約1小時）',
    references: [
      '《金匱要略》（張仲景）',
      '倪海廈《人紀·金匱要略》講義',
    ],
    keywords: ['金匱要略', '張仲景', '雜病', '痰飲', '水氣', '黃疸', '婦人病', '經方'],
    icon: '⚗',
    status: 'active',
    order: 5,
    slug: 'jingui',
    chapters: [
      {
        id: 'rj-jg-01',
        title: '雜病總論',
        subtitle: '病因病機與治則',
        description: '雜病的發病原因、病理機制與治療原則的總論。',
        keyPoints: [
          '內傷雜病與外感病的區別',
          '五臟風寒的辨證方法',
          '虛實寒熱的鑑別要點',
          '治未病的預防思想',
        ],
        order: 1,
      },
      {
        id: 'rj-jg-02',
        title: '痰飲水氣',
        subtitle: '痰飲四類與水腫治法',
        description: '痰飲、懸飲、溢飲、支飲四種痰飲病的辨證論治，以及水氣病的治療。',
        keyPoints: [
          '痰飲四類的鑑別',
          '水氣病（風水、皮水、正水、石水）',
          '苓桂術甘湯：痰飲病的基礎方',
          '五苓散：水氣病的常用方',
        ],
        order: 2,
      },
      {
        id: 'rj-jg-03',
        title: '婦人病與雜病各論',
        subtitle: '婦科與各科雜病',
        description: '婦人妊娠病、產後病、雜病以及其他各科雜病的辨證論治。',
        keyPoints: [
          '婦人妊娠病的治療原則',
          '產後三大病（痙、鬱冒、大便難）',
          '黃疸的辨證分型與治療',
          '胸痺（胸痛）的治療方劑',
        ],
        order: 3,
      },
    ],
  },
];

// ─── 215條針灸經驗穴位（倪師臨床精華） ────────────────────
export const ACU_EXPERIENCES: AcuExperience[] = [
  // 01 心·心血管系統
  { id: 1, condition: '冠心病', acupoints: '關元、巨闕、少府、湧泉、公孫', category: '心血管' },
  { id: 2, condition: '心臟肥大', acupoints: '巨闕、少府、神門、勞宮、關元、公孫、內關、天突', category: '心血管' },
  { id: 3, condition: '心絞痛', acupoints: '厲兌、人中、十宣（放血）、湧泉、百會（放血）', category: '心血管' },
  { id: 4, condition: '真心痛', acupoints: '巨闕、關元、天突、厲兌', category: '心血管' },
  { id: 5, condition: '心律不齊', acupoints: '關元、太淵', category: '心血管' },
  { id: 6, condition: '心悸', acupoints: '神門、少府、關元', category: '心血管' },
  { id: 7, condition: '心臟痛', acupoints: '公孫、內關、巨闕、關元、天突、厲兌', category: '心血管' },
  // 02 肝膽系統
  { id: 8, condition: '肝病', acupoints: '肝關、行間', category: '肝膽' },
  { id: 9, condition: '肝炎', acupoints: '行間', category: '肝膽' },
  { id: 10, condition: '肝硬化', acupoints: '肝俞、行間', category: '肝膽' },
  { id: 11, condition: '肝硬化腹水', acupoints: '水分、水道、肝關', category: '肝膽' },
  { id: 12, condition: '黃疸', acupoints: '脊中、行間', category: '肝膽' },
  { id: 13, condition: '膽結石', acupoints: '肝俞、膽俞、陽陵泉正下約一寸處（膽石點）', category: '肝膽' },
  // 03 脾胃消化系統
  { id: 14, condition: '胃病胃痛', acupoints: '中脘（梅花灸）、關元、天樞、公孫、內關', category: '脾胃' },
  { id: 15, condition: '胃癌', acupoints: '膺窗、魚際、足三里、天溪、痞根、地五會', category: '脾胃' },
  { id: 16, condition: '腹痛', acupoints: '三陰交、公孫、關元、中極、腸關', category: '脾胃' },
  { id: 17, condition: '腹脹', acupoints: '水分（灸）、公孫、消積', category: '脾胃' },
  { id: 18, condition: '胃酸過多', acupoints: '公孫、內關', category: '脾胃' },
  { id: 19, condition: '消化不良', acupoints: '公孫、內關、腹通谷', category: '脾胃' },
  { id: 20, condition: '嘔吐', acupoints: '公孫、內關、中脘、胃俞', category: '脾胃' },
  { id: 21, condition: '噁心反胃', acupoints: '中脘、公孫', category: '脾胃' },
  { id: 22, condition: '腹瀉', acupoints: '天樞、大橫、腸關、四滿', category: '脾胃' },
  { id: 23, condition: '便秘', acupoints: '支溝、照海', category: '脾胃' },
  { id: 24, condition: '痔瘡', acupoints: '長強、孔最、秩邊、承山', category: '脾胃' },
  { id: 25, condition: '便血', acupoints: '下髎', category: '脾胃' },
  { id: 26, condition: '結直腸癌', acupoints: '痞根、消積', category: '脾胃' },
  { id: 27, condition: '結核性腸炎', acupoints: '神闕（灸）、溫溜', category: '脾胃' },
  { id: 28, condition: '闌尾炎', acupoints: '闌尾、天樞、中脘、關元、足三里、肘尖（灸）', category: '脾胃' },
  { id: 29, condition: '疝氣', acupoints: '隱白、肝俞、大敦（對側）、行間', category: '脾胃' },
  { id: 30, condition: '水腫', acupoints: '水分、三陰交、地機、陰陵泉、水道', category: '脾胃' },
  // 04 肺·呼吸系統
  { id: 31, condition: '肺癌', acupoints: '中府、雲門、孔最、公孫、內關', category: '肺系' },
  { id: 32, condition: '氣喘', acupoints: '膻中、中府、雲門、孔最、公孫、內關', category: '肺系' },
  { id: 33, condition: '咳嗽', acupoints: '太淵、靈墟、俞府、彧中', category: '肺系' },
  { id: 34, condition: '多痰', acupoints: '豐隆', category: '肺系' },
  { id: 35, condition: '鼻子不通', acupoints: '迎香、合谷（對側）、通天', category: '肺系' },
  { id: 36, condition: '喉啞失聲', acupoints: '啞門（禁灸）', category: '肺系' },
  { id: 37, condition: '胸中瘀血', acupoints: '巨骨', category: '肺系' },
  { id: 38, condition: '肺結核', acupoints: '肺俞、膽俞、膈俞', category: '肺系' },
  { id: 39, condition: '肺積水', acupoints: '膈俞、膻中、鳩尾、陽穀、後溪、照海、水分、水道、大包', category: '肺系' },
  // 05 腎·泌尿系統
  { id: 40, condition: '腎虛', acupoints: '腎俞、京門、命門', category: '腎系' },
  { id: 41, condition: '遺精', acupoints: '三陰交（灸）、橫骨', category: '腎系' },
  { id: 42, condition: '前列腺肥大', acupoints: '陰陵泉、關元、足三里', category: '腎系' },
  { id: 43, condition: '陽強陽挺', acupoints: '蠡溝、曲泉', category: '腎系' },
  { id: 44, condition: '陰莖痛小腹痛', acupoints: '列缺、三陰交、次髎、大敦、行間', category: '腎系' },
  { id: 45, condition: '陰縮', acupoints: '大赫、大敦、行間', category: '腎系' },
  { id: 46, condition: '生殖器病', acupoints: '大敦', category: '腎系' },
  { id: 47, condition: '陰痛', acupoints: '少府', category: '腎系' },
  { id: 48, condition: '小便不利', acupoints: '中極、關元、三陰交、大鐘、陰包', category: '腎系' },
  { id: 49, condition: '小便痛', acupoints: '大敦、陰包', category: '腎系' },
  { id: 50, condition: '尿頻', acupoints: '中極、關元、陰陵泉', category: '腎系' },
  { id: 51, condition: '尿失禁', acupoints: '陰陵泉', category: '腎系' },
  { id: 52, condition: '腎結石', acupoints: '腎俞、京門、命門、交信和太溪之間（腎石點）', category: '腎系' },
  // 06 婦科·兒科
  { id: 53, condition: '痛經', acupoints: '關元（灸）、中極（灸）、三陰交、血海', category: '婦科' },
  { id: 54, condition: '月經過少', acupoints: '血海（血海下一寸針）', category: '婦科' },
  { id: 55, condition: '月經過多', acupoints: '隱白、行間', category: '婦科' },
  { id: 56, condition: '崩漏', acupoints: '隱白、交信、行間', category: '婦科' },
  { id: 57, condition: '赤白帶下', acupoints: '隱白、次髎、陰谷、大赫、白環俞', category: '婦科' },
  { id: 58, condition: '子宮肌瘤', acupoints: '下巨虛、地機、三陰交', category: '婦科' },
  { id: 59, condition: '子宮下垂', acupoints: '交信、大敦', category: '婦科' },
  { id: 60, condition: '陰道痙攣', acupoints: '大敦', category: '婦科' },
  { id: 61, condition: '陰道癢', acupoints: '曲泉', category: '婦科' },
  { id: 62, condition: '陰唇癢', acupoints: '陰交（灸）', category: '婦科' },
  { id: 63, condition: '不孕症', acupoints: '關元（灸）、氣衝、中極、上髎（灸）', category: '婦科' },
  { id: 64, condition: '孕吐', acupoints: '中脘、公孫', category: '婦科' },
  { id: 65, condition: '胎位不正', acupoints: '至陰', category: '婦科' },
  { id: 66, condition: '難產', acupoints: '支溝', category: '婦科' },
  { id: 67, condition: '胎盤不下', acupoints: '崑崙、太溪', category: '婦科' },
  { id: 68, condition: '產後惡露', acupoints: '中都', category: '婦科' },
  { id: 69, condition: '退乳斷奶', acupoints: '陷谷、上巨虛', category: '婦科' },
  { id: 70, condition: '乳房疼痛', acupoints: '神封、內庭', category: '婦科' },
  { id: 71, condition: '乳房腫脹', acupoints: '上巨虛、內庭', category: '婦科' },
  { id: 72, condition: '乳炎乳癱', acupoints: '內庭', category: '婦科' },
  { id: 73, condition: '乳腺小葉增生', acupoints: '上巨虛、天溪、地五會', category: '婦科' },
  { id: 74, condition: '乳房纖維瘤', acupoints: '天溪、地五會', category: '婦科' },
  { id: 75, condition: '乳腺癌', acupoints: '肩井、膺窗、魚際、足三里、天溪、痞根、地五會', category: '婦科' },
  // 07 神志·神經
  { id: 76, condition: '腦血栓', acupoints: '百會', category: '神志', note: '無昏迷時用' },
  { id: 77, condition: '中風', acupoints: '百會、風府', category: '神志' },
  { id: 78, condition: '中風中經絡', acupoints: '風市、陽陵泉、陰陵泉、懸鐘、三陰交', category: '神志' },
  { id: 79, condition: '半身不遂', acupoints: '環跳、風市、陰市、懸鐘', category: '神志' },
  { id: 80, condition: '週期性癱瘓', acupoints: '風市、陰市', category: '神志' },
  { id: 81, condition: '失眠', acupoints: '三毛（灸）、神門', category: '神志' },
  { id: 82, condition: '癲癇', acupoints: '申脈（灸）、照海（灸）、鳩尾、百會、人中、湧泉', category: '神志' },
  { id: 83, condition: '腦震盪', acupoints: '然谷（放血）', category: '神志' },
  { id: 84, condition: '紅斑狼瘡', acupoints: '心俞、肺俞、肝俞', category: '神志' },
  { id: 85, condition: '痴呆', acupoints: '懸鐘、痞根', category: '神志' },
  { id: 86, condition: '肋間神經痛', acupoints: '肝關', category: '神志' },
  { id: 87, condition: '癲狂', acupoints: '筋縮', category: '神志' },
  { id: 88, condition: '腦瘤', acupoints: '百會、湧泉', category: '神志' },
  // 08 傷痛外科
  { id: 89, condition: '頸椎病', acupoints: '崑崙、後溪、申脈', category: '傷科' },
  { id: 90, condition: '頭項強重', acupoints: '後溪、申脈、大杼、崑崙', category: '傷科' },
  { id: 91, condition: '落枕', acupoints: '手三里', category: '傷科' },
  { id: 92, condition: '五十肩', acupoints: '偏歷、條口、承山、曲池、二間', category: '傷科' },
  { id: 93, condition: '肩膀痠痛', acupoints: '肩中俞、肩外俞、曲池、肩井、足三里', category: '傷科' },
  { id: 94, condition: '肩拉傷', acupoints: '肩井、足三里', category: '傷科' },
  { id: 95, condition: '網球肘', acupoints: '曲池（拔罐放血）、手三里', category: '傷科' },
  { id: 96, condition: '手指痛', acupoints: '合谷透勞宮、三間透後溪', category: '傷科' },
  { id: 97, condition: '腰痛', acupoints: '委中、腎俞、大腸俞', category: '傷科' },
  { id: 98, condition: '坐骨神經痛', acupoints: '環跳、陽陵泉、委中、懸鐘', category: '傷科' },
  { id: 99, condition: '膝痛', acupoints: '風市、陰市、膝陽關透曲泉', category: '傷科' },
  { id: 100, condition: '腳扭傷', acupoints: '商丘透丘墟', category: '傷科', note: '一針見效' },
  // 09 五官科
  { id: 101, condition: '頭痛（前額）', acupoints: '合谷、陽白', category: '五官' },
  { id: 102, condition: '頭痛（偏頭）', acupoints: '太陽透率谷、絲竹空（放血）', category: '五官' },
  { id: 103, condition: '頭痛（後腦）', acupoints: '後溪、申脈、崑崙', category: '五官' },
  { id: 104, condition: '頭痛（頭頂）', acupoints: '陷谷透湧泉', category: '五官' },
  { id: 105, condition: '面癱', acupoints: '陽白透魚腰、地倉透頰車、絲竹空透太陽', category: '五官' },
  { id: 106, condition: '白內障', acupoints: '陽白透魚腰、睛明、球后、承泣、養老', category: '五官' },
  { id: 107, condition: '近視眼', acupoints: '陽白透魚腰、翳風、丘墟', category: '五官' },
  { id: 108, condition: '色盲', acupoints: '臂臑透肩髃、復溜、睛明、光明', category: '五官' },
  { id: 109, condition: '耳鳴', acupoints: '耳門、聽宮、聽會、腎俞、翳風', category: '五官' },
  { id: 110, condition: '牙痛', acupoints: '合谷、頰車、下關', category: '五官' },
  // 10 其他
  { id: 111, condition: '戒菸', acupoints: '列缺透陽溪、築賓、合谷、肺俞', category: '其他' },
  { id: 112, condition: '盜汗', acupoints: '神門透陰郄、內關', category: '其他' },
  { id: 113, condition: '狐臭', acupoints: '肩髃透極泉', category: '其他' },
  { id: 114, condition: '瘧疾', acupoints: '外關透內關、大椎、命門', category: '其他' },
  { id: 115, condition: '中暑昏厥', acupoints: '水溝透齦交、十宣放血', category: '其他' },
  { id: 116, condition: '皮膚癢', acupoints: '三間透合谷、築賓、至陰、曲池、血海', category: '其他' },
  { id: 117, condition: '腳跟痛', acupoints: '大陵透足根點、承山、僕參、水泉', category: '其他' },
  { id: 118, condition: '靜脈曲張', acupoints: '三陰交、足三里、承山、委中', category: '其他' },
  { id: 119, condition: '發燒', acupoints: '大椎、曲池、合谷、外關', category: '其他' },
  { id: 120, condition: '感冒', acupoints: '風池、風府、大椎、合谷', category: '其他' },
];

// ─── 31條透針透穴法 ────────────────────────────────────────
export const TRANS_NEEDLING: TransNeedling[] = [
  { id: 1, combo: '中府透雲門', indication: '咳嗽、氣喘、哮喘、肺癌', supporting: '孔最、公孫、內關', source: '倪海廈' },
  { id: 2, combo: '陽陵泉透陰陵泉', indication: '中風、中經絡、雷諾氏病', supporting: '內關、水溝、三陰交、極泉', source: '孫培榮/周左宇/倪海廈' },
  { id: 3, combo: '懸鐘透三陰交', indication: '中風、肩膀痛、上肢神經痛', supporting: '陽陵泉', source: '孫培榮/周左宇/倪海廈' },
  { id: 4, combo: '曲池透少海', indication: '半身不遂、偏癱', supporting: '先針健側瀉法再針患側補法', source: '孫培榮' },
  { id: 5, combo: '水溝透齦交', indication: '暈倒、暈厥', supporting: '湧泉、關元、豐隆', source: '周左宇' },
  { id: 6, combo: '四神聰透百會', indication: '痴呆', supporting: '印堂、神庭、上星、風池', source: '孫培榮' },
  { id: 7, combo: '神庭透上星', indication: '腦癱、智力低下', supporting: '四神聰、百會、印堂、風池', source: '孫培榮' },
  { id: 8, combo: '液門透中渚', indication: '臂叢神經痛', supporting: '三間', source: '孫培榮' },
  { id: 9, combo: '合谷透勞宮', indication: '雷諾氏病', supporting: '內關、太淵、陰陵泉、陽陵泉', source: '孫培榮' },
  { id: 10, combo: '條口透承山', indication: '肩膀諸痛', supporting: '陽陵泉、曲垣、肩井', source: '孫培榮/周左宇/倪海廈' },
  { id: 11, combo: '懸鐘透三陰交+天髎透曲垣', indication: '肩胛痛、膏肓痛', supporting: '郄門、曲池、肩井、足三里', source: '孫培榮/周左宇/倪海廈' },
  { id: 12, combo: '養老透間使', indication: '臂痛、肘痛', supporting: '液門、中渚、曲池', source: '孫培榮/周左宇/倪海廈' },
  { id: 13, combo: '陷谷透湧泉', indication: '手痛諸證', supporting: '小海、外關、合谷', source: '倪海廈' },
  { id: 14, combo: '三間透勞宮', indication: '手痛、手脹、手木、手麻', supporting: '曲池、肩井、外關', source: '倪海廈' },
  { id: 15, combo: '合谷透勞宮/三間透後溪', indication: '手指痛', source: '倪海廈' },
  { id: 16, combo: '膝陽關透曲泉', indication: '膝蓋諸疾', supporting: '風市、陰市', source: '孫培榮' },
  { id: 17, combo: '商丘透丘墟', indication: '腳扭傷', source: '倪海廈' },
  { id: 18, combo: '大陵透足根點', indication: '腳跟痛', supporting: '承山、僕參、水泉', source: '孫培榮' },
  { id: 19, combo: '膝陽關透曲泉', indication: '曲池少海部位不適', source: '孫培榮/周左宇' },
  { id: 20, combo: '三間透合谷', indication: '皮膚癢', supporting: '築賓、至陰、屋翳、內庭、曲池、血海', source: '孫培榮' },
  { id: 21, combo: '陽白透魚腰+絲竹空透太陽+地倉透頰車', indication: '面癱、口眼歪斜', supporting: '先健後患', source: '孫培榮/周左宇/倪海廈' },
  { id: 22, combo: '陽白透魚腰', indication: '白內障、近視眼', supporting: '睛明、球后、承泣、養老、翳風、丘墟', source: '倪海廈' },
  { id: 23, combo: '太陽透率谷', indication: '偏頭痛', supporting: '對側合谷麻醉、絲竹空放血、然谷', source: '孫培榮' },
  { id: 24, combo: '陷谷透湧泉', indication: '百會痛（頭頂痛）', source: '孫培榮' },
  { id: 25, combo: '臂臑透肩髃', indication: '色盲、視神經萎縮', supporting: '復溜、睛明、絲竹空、光明', source: '孫培榮/周左宇' },
  { id: 26, combo: '攢竹透魚腰/絲竹空透魚腰', indication: '眼睛不閉、眉稜骨痛', supporting: '陽陵泉', source: '孫培榮' },
  { id: 27, combo: '液門透中渚', indication: '耳鳴', supporting: '翳風、耳門、聽會、腎俞', source: '周左宇' },
  { id: 28, combo: '列缺透陽溪', indication: '戒菸', supporting: '築賓、合谷、肺俞', source: '孫培榮' },
  { id: 29, combo: '神門透陰郄', indication: '盜汗、手汗', supporting: '內關、手五里、間使', source: '周左宇' },
  { id: 30, combo: '外關透內關', indication: '瘧疾', supporting: '大椎、命門、委中', source: '孫培榮' },
  { id: 31, combo: '肩髃透極泉', indication: '狐臭', source: '倪海廈' },
];

// ─── 漢唐100方完整列表 ────────────────────────────────────
export const HANTANG_FORMULAS: HantangFormula[] = [
  { id: 1, name: '白帶丸', indication: '女性赤白帶過多', theory: '乳汁下行變化為月經，肝經主疏洩' },
  { id: 2, name: '退乳丸', indication: '退乳汁，預防乳癌', theory: '乳汁與月經同源' },
  { id: 3, name: '補髓丹', indication: '記憶力減退、老年痴呆', theory: '腦為髓海，髓源於腎精', ingredients: '杜仲、補骨脂、鹿茸、沒藥、核桃肉' },
  { id: 4, name: '皮膚過敏丸', indication: '食物過敏引起皮膚紅疹瘙癢', theory: '脾胃功能不足致過敏' },
  { id: 5, name: '通乳丸', indication: '乳汁不足、乳房硬塊', theory: '加強心臟熱能使乳汁下行', ingredients: '附子、生薑、柴胡、黃芩、桂枝、半夏' },
  { id: 6, name: '手抖心顫方', indication: '手抖、心顫、心臟病早期', theory: '心火不足致心臟壓縮力不衡', ingredients: '半夏、桂枝、黃連、白朮' },
  { id: 7, name: '胃癰方', indication: '胃癰及胃出血', theory: '血不歸經則出血' },
  { id: 8, name: '子宮症痼方', indication: '子宮肌瘤、子宮腫瘤', theory: '加強心臟熱能使瘀血排出', ingredients: '桂枝、茯苓、丹皮、白芍' },
  { id: 9, name: '血箭痔丸', indication: '大便前出血如箭射', theory: '小腸溼熱下注', ingredients: '百草霜、梔子花、榴花、地榆' },
  { id: 10, name: '大禹丸', indication: '肝癌末期腹腔積水', theory: '大禹治水排腹水', ingredients: '十棗湯加減' },
  { id: 11, name: '代抵當丸', indication: '子宮幹血、膀胱蓄血', theory: '破血活血排除瘀血', ingredients: '水蛭、虻蟲、桃仁、大黃' },
  { id: 12, name: '脫肛丸', indication: '脫肛、肛門下墜', theory: '中氣下陷致直腸脫垂' },
  { id: 13, name: '淋痛方', indication: '小便刺痛、淋症', theory: '相火外洩、熱結下焦' },
  { id: 14, name: '膽石方', indication: '膽結石、膽囊息肉', theory: '肝氣鬱滯、膽汁排洩不利' },
  { id: 15, name: '真寒假熱方', indication: '血癌、白血病', theory: '陽氣過亢、陰液不足' },
  { id: 16, name: '幹癢癬方', indication: '皮膚乾燥、牛皮癬', theory: '肺主皮毛，強化肺津液輸布' },
  { id: 17, name: '溼疹膿瘡方', indication: '皮膚溼疹、黃水瘡', theory: '脾運化不足致脾溼腸燥' },
  { id: 18, name: '蛇方', indication: '帶狀皰疹', theory: '經絡不通、火氣上逆' },
  { id: 19, name: '焦慮方', indication: '氣血兩虛型焦慮抑鬱', theory: '肺主氣心主血不足' },
  { id: 20, name: '四肢無力方', indication: '下肢無力、肌肉萎縮', theory: '脾運化功能不足' },
  { id: 21, name: '補陽還五丸', indication: '中風後遺症、癱瘓', theory: '氣虛血瘀阻滯腦部' },
  { id: 22, name: '奔豚湯', indication: '奔豚氣、腹部動悸', theory: '濁氣上衝、氣機錯亂' },
  { id: 23, name: '降壓方', indication: '高血壓、中風預防', theory: '肝升肺斂失衡', ingredients: '桔梗、五味子、桃仁、丹皮' },
  { id: 24, name: '消渴方', indication: '糖尿病、消渴症', theory: '脾運化不足致血糖失常', ingredients: '山茱萸、生地、石膏' },
  { id: 25, name: '疏通經絡劑', indication: '三叉神經痛', theory: '經絡不通、火氣上逆' },
  { id: 26, name: '石淋方', indication: '腎結石、尿路結石', theory: '肝鬱相火煎熬水液成石' },
  { id: 27, name: '痛風丸', indication: '痛風、關節紅腫劇痛', theory: '鬱則生風、毒氣積聚關節' },
  { id: 28, name: '風溼丸', indication: '風溼性關節炎', theory: '風寒溼三邪痰飲停留關節' },
  { id: 29, name: '消痔丸', indication: '外痔瘡、肛門痛癢', theory: '升氣血解毒' },
  { id: 30, name: '坐骨神經痛方', indication: '坐骨神經痛、腰痛', theory: '經絡堵塞、椎間盤突出壓迫' },
  { id: 31, name: '三酸甘油脂方', indication: '三酸甘油脂過高', theory: '中焦溼熱過盛' },
  { id: 32, name: '烏金丸', indication: '心痛澈背、背痛澈心', theory: '心臟病前兆' },
  { id: 33, name: '溼熱便秘方', indication: '中焦溼熱兼便秘', theory: '溼熱壅結大腸' },
  { id: 34, name: '補天丸', indication: '掉頭髮、耳鳴', theory: '腎精不足' },
  { id: 35, name: '紫金丹', indication: '胸腔內傷、上身瘀血', theory: '活血化瘀' },
  { id: 36, name: '天青丸', indication: '婦女痛經、下身瘀血', theory: '增加小腸熱量促進靜脈迴流' },
  { id: 37, name: '天威丸', indication: '男性精子不足', theory: '補腎壯精' },
  { id: 38, name: '玉華丸', indication: '女性滋補', theory: '滋補陰液' },
  { id: 39, name: '鼻淵丸', indication: '鼻塞不通、流清涕', theory: '溫肺通竅' },
  { id: 40, name: '烏梅丸', indication: '各種寄生蟲、蛔蟲', theory: '驅蟲安蛔' },
  { id: 41, name: '中安丸', indication: '失眠', theory: '交通心腎' },
  { id: 42, name: '控涎丹', indication: '痰阻塞胸肺、癲癇', theory: '攻逐痰飲' },
  { id: 43, name: '麻子仁丸', indication: '大便如羊屎小顆粒', theory: '潤腸通便' },
  { id: 44, name: '皂莢丸', indication: '清除肺中吸菸濁痰', theory: '滌痰清肺' },
  { id: 45, name: '己椒藶黃丸', indication: '右腹脹、腸間水氣', theory: '分消溼熱水飲' },
  { id: 46, name: '六味地黃丸', indication: '滋陰補腎通用', theory: '三補三瀉' },
  { id: 47, name: '重陽丸', indication: '男子精中帶血', theory: '固腎清相火' },
  { id: 48, name: '金匱腎氣丸', indication: '手腳冰冷、強化腎臟', theory: '補腎助陽' },
  { id: 49, name: '起陽丸', indication: '振奮陽氣、增強性功能', theory: '生精壯陽' },
  { id: 50, name: '牙痛止痛劑', indication: '牙痛', theory: '清熱止痛' },
  { id: 52, name: '赤丸', indication: '心臟肥大、動脈剝離', theory: '心陽不足致心臟代償肥大', ingredients: '半夏、枳實、炙甘草' },
  { id: 53, name: '風引湯', indication: '風痱（中風後四肢無力）', theory: '排出骨節深層風寒溼' },
  { id: 54, name: '喉蛾方', indication: '扁桃腺發炎', theory: '相火不收藏衝擊咽喉' },
  { id: 55, name: '紫雲膏', indication: '皮膚生堅結（外用）', theory: '活血化瘀外用' },
  { id: 56, name: '漢唐紅', indication: '外用傷口特效藥', theory: '活血生肌' },
  { id: 57, name: '佛州黑', indication: '外用燙傷特效藥', theory: '清熱生肌' },
  { id: 58, name: '白內障藥水', indication: '白內障（外用）', theory: '外用通竅明目' },
  { id: 59, name: '噴鼻藥粉', indication: '鼻炎過敏、昏迷急救', theory: '開腦竅刺激鼻竇' },
  { id: 60, name: '強力天青丸', indication: '雙足靜脈曲張', theory: '增強小腸熱量促進靜脈迴流' },
  { id: 61, name: '明目地黃丸', indication: '眼睛保養、視力不足', theory: '肝開竅在眼、補肝明目' },
  { id: 62, name: '沉香桂附丸', indication: '少腹痛、下利、雙足冷', theory: '沉香引火歸元溫腎氣' },
  { id: 63, name: '骨損方', indication: '骨質疏鬆症', theory: '腎主骨、補腎強骨' },
  { id: 64, name: '更年期方', indication: '經停後身熱盜汗', theory: '子宮萎縮熱能回逆三焦' },
  { id: 65, name: '膀胱結石方', indication: '膀胱結石、尿道炎', theory: '清利溼熱' },
  { id: 66, name: '前列腺方', indication: '前列腺肥大、膀胱無力', theory: '增強膀胱氣化功能' },
  { id: 67, name: '失心丸', indication: '癲癇發狂', theory: '陰喬陽喬失衡、清肺痰' },
  { id: 68, name: '護肝丸', indication: '乙肝及各類肝病', theory: '見肝之病知肝傳脾當先實脾' },
  { id: 69, name: '腎積水方', indication: '腎積水、下肢水腫', theory: '恢復腎臟排尿功能' },
  { id: 70, name: '定心丸', indication: '心腎不交、焦慮憂鬱', theory: '心火下行腎水上升' },
  { id: 71, name: '清鬱開結丸', indication: '強烈沮喪、憂鬱感', theory: '肝鬱脾結開鬱升肝木' },
  { id: 72, name: '浮萍方', indication: '小兒風癢、皮膚病', theory: '浮萍辛涼利溼止癢' },
  { id: 73, name: '透膿方', indication: '四肢末梢壞疽', theory: '增加小腸熱力驅邪生肌' },
  { id: 74, name: '搜風解毒湯', indication: '性病泡疹淋病梅毒', theory: '清除病毒由小便排出' },
  { id: 75, name: '枕中丹', indication: '令人聰明', theory: '補腦益智' },
  { id: 76, name: '避孕丸', indication: '避孕', theory: '中藥避孕' },
  { id: 77, name: '心絞痛方', indication: '心臟動脈阻塞', theory: '清肝毒排血管瘀物' },
  { id: 78, name: '健胃散', indication: '各種胃病', theory: '溫降調理胃氣' },
  { id: 79, name: '青春痘方', indication: '青春痘', theory: '相火旺盛排毒表現' },
  { id: 80, name: '減肥丸', indication: '過胖症', theory: '心臟是唯一控制體重的臟器' },
  { id: 81, name: '鼻過敏頭痛方', indication: '鼻過敏合併頭痛', theory: '鼻竅堵塞阻斷氣血', ingredients: '白附子、殭蠶' },
  { id: 82, name: '下焦寒實方', indication: '前列腺癌', theory: '導引心熱下行至小腸', ingredients: '炮附、細辛、五味子、丹皮、木通、桂枝' },
  { id: 83, name: '皮膚諸病粉', indication: '皮膚生瘡化膿（外用）', theory: '去溼化膿生新皮', ingredients: '密陀僧、雄黃' },
  { id: 84, name: '肝結石方', indication: '膽切除後肝結石', theory: '失去膽吸力致膽汁積滯', ingredients: '柴胡、枳實、黃芩、鬱金、海金沙' },
  { id: 85, name: '青春痘外用粉', indication: '青春痘（外用）', theory: '滋潤清炎' },
  { id: 86, name: '腳氣方', indication: '腳氣病香港腳（外用）', theory: '殺菌除溼' },
  { id: 87, name: '心臟肥大方', indication: '心臟肥大症', theory: '心陽不足代償性變化' },
  { id: 88, name: '磁珠丸', indication: '白內障、青光眼', theory: '磁石收納腎氣交通心腎', ingredients: '磁石、決明子、神曲' },
  { id: 89, name: '健筋骨丸', indication: '骨折、肌肉萎縮、坐骨神經痛', theory: '肝主筋腎主骨乙癸同源' },
  { id: 90, name: '消瘤丸', indication: '甲狀腺腫瘤（大脖子）', theory: '陽氣行則陰不積' },
  { id: 92, name: '增高丸', indication: '身材矮小', theory: '補腎精同時收斂陰成形' },
  { id: 93, name: '小兒過動症方', indication: '多動症ADHD', theory: '心火上炎腎水不濟', ingredients: '木通、附子' },
  { id: 95, name: '拖裡化毒飲', indication: '淋巴膿塊、乳房膿塊', theory: '裡拖毒外拔毒相結合' },
  { id: 96, name: '乳癌外用粉', indication: '乳癌膿塊（外用）', theory: '外用拔毒' },
  { id: 97, name: '何首烏丸', indication: '白髮、延年益壽', theory: '何首烏補肝血養精氣' },
  { id: 98, name: '五石烏頭丸', indication: '嚴重癌症、嚴重風溼', theory: '金石丹藥攻力猛', ingredients: '鍾乳、硫磺、礬石、紫石英、赤石脂、烏頭、附子等32味' },
  { id: 99, name: '斑龍丸', indication: '腦受損、腎陰陽兩虛', theory: '鹿角鹿茸補厥下海底陰' },
  { id: 100, name: '歷節丸', indication: '類風溼性關節炎', theory: '源自金匱烏頭湯症', ingredients: '生烏頭' },
];

// ─── 核心經方精選（傷寒論+金匱要略） ──────────────────────
export const CLASSIC_FORMULAS: ClassicFormula[] = [
  { id: 'cf-01', name: '桂枝湯', source: '傷寒論', composition: '桂枝10g、白芍10g、生薑二片、炙甘草10g、紅棗十枚', indication: '太陽中風，調和營衛', niUsage: '太陽中風第一方，脈浮緩有汗惡風' },
  { id: 'cf-02', name: '麻黃湯', source: '傷寒論', composition: '麻黃9g、桂枝6g、杏仁9g、炙甘草3g', indication: '太陽傷寒，發汗解表', niUsage: '脈浮緊無汗惡寒身疼' },
  { id: 'cf-03', name: '小柴胡湯', source: '傷寒論', composition: '柴胡24g、黃芩9g、半夏9g、生薑9g、人參9g、甘草6g、大棗12枚', indication: '和解少陽', niUsage: '往來寒熱胸脅苦滿' },
  { id: 'cf-04', name: '白虎湯', source: '傷寒論', composition: '石膏50g、知母18g、甘草6g、粳米一合', indication: '清陽明裡熱', niUsage: '壯熱汗出大渴大煩' },
  { id: 'cf-05', name: '四逆湯', source: '傷寒論', composition: '附子一枚、乾薑9g、炙甘草6g', indication: '回陽救逆', niUsage: '少陰寒化主方，四肢厥冷脈微細' },
  { id: 'cf-06', name: '小青龍湯', source: '傷寒論', composition: '麻黃12g、芍藥9g、乾薑9g、半夏9g、桂枝6g、炙甘草6g、細辛3g、五味子3g', indication: '表寒裡寒伴水飲', niUsage: '外寒內飲咳喘痰多清稀' },
  { id: 'cf-07', name: '大青龍湯', source: '傷寒論', composition: '麻黃12g、桂枝6g、杏仁6g、石膏如雞蛋大、甘草6g、生薑9g、大棗12枚', indication: '表實裡熱', niUsage: '惡寒無汗煩躁' },
  { id: 'cf-08', name: '葛根湯', source: '傷寒論', composition: '葛根12g、麻黃9g、桂枝6g、芍藥6g、甘草6g、生薑9g、大棗12枚', indication: '太陽陽明合病項背強', niUsage: '項背強几几、下利' },
  { id: 'cf-09', name: '真武湯', source: '傷寒論', composition: '附子一枚、茯苓9g、白朮6g、芍藥9g、生薑9g', indication: '陽虛水泛', niUsage: '心下悸、頭眩、身瞤動' },
  { id: 'cf-10', name: '理中湯', source: '傷寒論', composition: '人參9g、白朮9g、乾薑9g、甘草9g', indication: '中焦虛寒', niUsage: '腹痛吐利、四肢不溫' },
  { id: 'cf-11', name: '苓桂術甘湯', source: '金匱', composition: '茯苓12g、桂枝9g、白朮6g、甘草6g', indication: '痰飲病基礎方', niUsage: '心下逆滿氣上衝胸頭眩' },
  { id: 'cf-12', name: '五苓散', source: '傷寒論', composition: '豬苓9g、澤瀉15g、茯苓9g、白朮9g、桂枝6g', indication: '水氣病', niUsage: '小便不利、渴欲飲水' },
  { id: 'cf-13', name: '桂枝加葛根湯', source: '傷寒論', composition: '桂枝湯加葛根12g', indication: '太陽中風項背強', niUsage: '項背強几几有汗' },
  { id: 'cf-14', name: '桂枝加厚朴杏仁湯', source: '傷寒論', composition: '桂枝湯加厚朴、杏仁', indication: '表證兼咳喘', niUsage: '太陽中風兼喘' },
  { id: 'cf-15', name: '麻杏甘石湯', source: '傷寒論', composition: '麻黃6g、杏仁9g、甘草6g、石膏24g', indication: '發汗後咳喘熱盛', niUsage: '汗出而喘' },
  { id: 'cf-16', name: '大承氣湯', source: '傷寒論', composition: '大黃12g、芒硝9g、厚朴15g、枳實12g', indication: '陽明腑實證', niUsage: '痞滿燥實四證俱全' },
  { id: 'cf-17', name: '小承氣湯', source: '傷寒論', composition: '大黃12g、厚朴6g、枳實9g', indication: '陽明腑實輕證', niUsage: '痞滿不燥實' },
  { id: 'cf-18', name: '當歸四逆湯', source: '傷寒論', composition: '當歸9g、桂枝9g、芍藥9g、細辛3g、通草6g、甘草6g、大棗25枚', indication: '血虛寒凝手足厥冷', niUsage: '手足厥寒、脈細欲絕' },
  { id: 'cf-19', name: '烏梅丸', source: '傷寒論', composition: '烏梅30枚、細辛6g、乾薑10g、黃連9g、當歸4g、附子6g、蜀椒4g、桂枝6g、人參6g、黃柏6g', indication: '厥陰病寒熱錯雜蛔厥', niUsage: '消渴氣上撞心飢而不欲食' },
  { id: 'cf-20', name: '炙甘草湯', source: '傷寒論', composition: '炙甘草12g、生薑9g、人參6g、生地黃48g、桂枝9g、阿膠6g、麥冬12g、麻仁12g、大棗30枚', indication: '心動悸脈結代', niUsage: '氣血不足心律不齊' },
  { id: 'cf-21', name: '腎氣丸', source: '金匱', composition: '乾地黃24g、山藥12g、山茱萸12g、澤瀉9g、茯苓9g、丹皮9g、桂枝3g、炮附子3g', indication: '腎陽不足', niUsage: '腰痛腳軟小便不利' },
  { id: 'cf-22', name: '桂枝茯苓丸', source: '金匱', composition: '桂枝、茯苓、丹皮、桃仁、芍藥各等分', indication: '瘀血阻滯胞宮', niUsage: '妊娠下血不止、子宮肌瘤' },
  { id: 'cf-23', name: '溫經湯', source: '金匱', composition: '吳茱萸9g、當歸6g、芍藥6g、川芎6g、人參6g、桂枝6g、阿膠6g、丹皮6g、生薑6g、甘草6g、半夏6g、麥冬9g', indication: '衝任虛寒瘀血阻滯', niUsage: '婦人少腹寒、久不受胎' },
  { id: 'cf-24', name: '防己黃芪湯', source: '金匱', composition: '防己12g、黃芪15g、白朮9g、甘草6g、生薑4片、大棗1枚', indication: '風水、風溼表虛', niUsage: '汗出惡風身重小便不利' },
  { id: 'cf-25', name: '小建中湯', source: '傷寒論', composition: '桂枝9g、芍藥18g、甘草6g、生薑9g、大棗12枚、飴糖30g', indication: '中焦虛寒腹痛', niUsage: '腹中急痛、虛勞' },
];

// ─── 統計 ────────────────────────────────────────────────
export const RENJI_STATS = {
  totalModules: RENJI_MODULES.length,
  totalChapters: RENJI_MODULES.reduce((sum, m) => sum + m.chapters.length, 0),
  totalLessons: '150+集',
  completionYear: '2004-2005',
  learningOrder: ['針灸大成', '黃帝內經', '神農本草經', '傷寒論', '金匱要略'],
  acuExperienceCount: 215,
  transNeedlingCount: 31,
  hantangFormulaCount: 100,
  classicFormulaCount: 259,
};
