/**
 * 天紀 — 倪海廈天文術數體系資料庫
 *
 * 「上知天文」—— 天之紀，是術數研究的體系化成果。
 * 1994年錄製，共24集影片（每集2小時，共48小時）。
 * 講義分為《天機道》《人間道》《地脈道》《64卦易圖》四冊。
 *
 * 核心學派：
 *   紫微斗數 → 三合派
 *   風水     → 九星派（楊救貧流派）
 *   易經     → 象數派
 *   推命     → 河洛數理派
 */

import type { NiModule, Hexagram, FengShuiEntry, TianjiEpisode } from './types';

// ─── 天紀模組 ────────────────────────────────────────────
export const TIANJI_MODULES: NiModule[] = [
  {
    id: 'tj-ziwei',
    category: 'tianji',
    name: '紫微斗數',
    nameEn: 'Zi Wei Dou Shu',
    subtitle: '三合派 · 倪師正宗體系',
    description: '以紫微星為主軸，十四主星配十二宮位，結合四化星推演人生格局。倪師主張「大道至簡」，不用飛星派複雜化法，以三合派為正宗。',
    details: [
      '紫微斗數是倪師天紀課程的核心命學工具，屬三合派體系。倪師明言：「飛星（四化）飛來飛去太複雜，不搞這個，畢竟大道至簡。」',
      '課程以十二張案例講義為教材，紫微星在十二個位置各一張，從子宮到亥宮繞一圈，覆蓋所有主星排列。',
      '倪師強調命宮為本、三方為用——命宮主星決定基本格局與天生性格，三方（財帛、官祿、遷移）決定用武之地。',
      '四化星（化祿、化權、化科、化忌）的運用是核心技法，配合大限流年推演人生關鍵節點。',
    ],
    school: '三合派',
    lessons: '天紀影片前半部分（約24小時）',
    references: [
      '《紫微斗數全集》',
      '《紫微斗數全書》',
      '《骨髓賦》',
      '倪海廈《天紀》講義（天機道篇）',
    ],
    keywords: ['紫微斗數', '三合派', '十四主星', '十二宮位', '四化星', '大限', '流年', '命宮', '三方四正', '格局'],
    icon: '◉',
    status: 'active',
    order: 1,
    slug: 'ziwei',
    chapters: [
      {
        id: 'tj-zw-01',
        title: '紫微斗數基礎',
        subtitle: '安星法與排盤原理',
        description: '從年支排盤入手，瞭解紫微斗數的基本安星規則、十二宮位的含義與相互關係。',
        keyPoints: [
          '以年支排盤，非子平法的年柱排列',
          '十二宮位：命宮、兄弟、夫妻、子女、財帛、疾厄、遷移、交友、官祿、田宅、福德、父母',
          '命宮為一切分析的起點',
          '身宮可看影響最重的宮位',
        ],
        quotes: ['身宮在財帛宮的女孩子，一般來說就是職業婦女'],
        order: 1,
      },
      {
        id: 'tj-zw-02',
        title: '十四主星詳解',
        subtitle: '星性與廟旺利陷',
        description: '深入講解紫微、天機、太陽、武曲、天同、廉貞、天府、太陰、貪狼、巨門、天相、天梁、七殺、破軍十四顆主星的性質。',
        keyPoints: [
          '每顆主星有獨特的性格特質與命理意涵',
          '亮度系統（廟/旺/得/利/平/不/陷）影響星力發揮',
          '殺破狼三星一定同在三方，構成變動格局',
          '紫微星為帝座，天府為財庫',
        ],
        quotes: ['最怕的是七殺臨身，七殺臨身的人一輩子多敗少成'],
        order: 2,
      },
      {
        id: 'tj-zw-03',
        title: '四化星運用',
        subtitle: '化祿化權化科化忌',
        description: '四化星是紫微斗數的靈魂技法，每年天干對應四顆星化入不同宮位，推動命運變化。',
        keyPoints: [
          '化祿星主財，性守——代表財運和享受',
          '化權星性剛，代表官印——代表權力和掌控',
          '化科星主科名，名氣很大——代表名聲和貴人',
          '化忌星主劫殺——代表阻礙和困難',
          '大限四化與流年四化疊加判斷',
        ],
        order: 3,
      },
      {
        id: 'tj-zw-04',
        title: '格局與斷命',
        subtitle: '經典格局與實戰案例',
        description: '從殺破狼、火貪格等經典格局入手，結合倪師十二張案例講義實戰斷命。',
        keyPoints: [
          '官祿宮最喜歡權星入進來',
          '殺破狼格局代表變動與開創',
          '火貪格主暴發',
          '命相同參可提高準確率',
          '結合面相（五形論）輔助判斷',
        ],
        order: 4,
      },
    ],
  },
  {
    id: 'tj-yijing',
    category: 'tianji',
    name: '易經六十四卦',
    nameEn: 'Yi Jing 64 Hexagrams',
    subtitle: '象數派 · 斷易天機',
    description: '倪師以《斷易天機》為底本，自創圖示法講解六十四卦，前一小時講命學，後一小時講易經，相輔相成。',
    details: [
      '易經部分以象數派為主，倪師自行演變的易圖是獨特教學工具，極大簡化了學習難度。',
      '64卦圖解底本來自《斷易天機》，倪師重新排列、註解，形成獨有的圖示教學法。',
      '課程不僅教卦理，更注重實際占卜應用：如何起卦、解卦、斷事。',
      '倪師強調易經不僅是占卜工具，更是決策智慧——「不但看到時機，還能馬上做決策」。',
    ],
    school: '象數派',
    lessons: '天紀影片後半部分（約24小時）',
    references: [
      '《斷易天機》',
      '《周易》',
      '倪海廈《人間道·64卦易圖》',
    ],
    keywords: ['易經', '六十四卦', '八卦', '象數派', '占卜', '斷易天機', '圖示法', '六爻'],
    icon: '☰',
    status: 'active',
    order: 2,
    slug: 'yijing',
    chapters: [
      {
        id: 'tj-yj-01',
        title: '易經基礎與八卦',
        subtitle: '陰陽與先後天八卦',
        description: '從太極生兩儀、兩儀生四象、四象生八卦入手，建立易經的基礎知識體系。',
        keyPoints: [
          '乾（天）、兌（澤）、離（火）、震（雷）、巽（風）、坎（水）、艮（山）、坤（地）',
          '先天八卦與後天八卦的區別',
          '八卦的象徵意義與自然對應',
          '六爻的由來與結構',
        ],
        order: 1,
      },
      {
        id: 'tj-yj-02',
        title: '六十四卦詳解',
        subtitle: '圖示法與卦辭解讀',
        description: '逐卦講解六十四卦的卦象、卦辭、爻辭要義，配合倪師獨創圖示法。',
        keyPoints: [
          '每卦由上下兩個三爻卦疊合而成',
          '卦辭揭示整體趨勢，爻辭指示具體位置',
          '變卦（動爻）是斷事的關鍵',
          '倪師圖解簡化了傳統解卦的複雜性',
        ],
        order: 2,
      },
      {
        id: 'tj-yj-03',
        title: '占卜實戰',
        subtitle: '起卦與斷事方法',
        description: '從起卦方法到斷事技巧，覆蓋完整的占卜實戰流程。',
        keyPoints: [
          '多種起卦法：揲蓍法、金錢卦、梅花易數等',
          '用神取用與六親關係',
          '六神（青龍、朱雀、勾陳、騰蛇、白虎、玄武）占斷',
          '時間、方位、事態的綜合判斷',
        ],
        order: 3,
      },
    ],
  },
  {
    id: 'tj-kanyu',
    category: 'tianji',
    name: '堪輿學',
    nameEn: 'Kan Yu Xue',
    subtitle: '九星派 · 楊救貧流派',
    description: '涵蓋陽宅風水與陰宅選擇，以九星派（楊救貧流派）為正宗，講解三吉六秀、八煞黃泉等核心風水理論。',
    details: [
      '堪輿學是天紀課程「下知地理」的核心板塊，屬於《地脈道》講義內容。',
      '倪師採用楊救貧九星派體系，強調巒頭（山形水勢）與理氣（方位吉凶）並重。',
      '陽宅部分講解居住環境對人生的影響，包括房屋朝向、內部佈局、周圍環境等。',
      '陰宅部分講解墓地選擇與立向，強調「八煞黃泉」是絕對禁忌的方位。',
      '倪師認為「人事的努力加上地理上的調整，一定能大於先天的命運」，即2/3大於1/3的核心理念。',
    ],
    school: '九星派（楊救貧流派）',
    lessons: '天紀影片第18-21集',
    references: [
      '倪海廈《地脈道》講義',
      '楊救貧風水典籍',
    ],
    keywords: ['堪輿', '風水', '陽宅', '陰宅', '九星派', '楊救貧', '八煞黃泉', '三吉六秀', '巒頭', '理氣'],
    icon: '⊞',
    status: 'active',
    order: 3,
    slug: 'kanyu',
    chapters: [
      {
        id: 'tj-ky-01',
        title: '陽宅風水',
        subtitle: '居住環境與人生運勢',
        description: '講解住宅選擇與佈局的風水原理，包括朝向、格局、周圍環境對居住者的影響。',
        keyPoints: [
          '三吉方向（生氣、延年、天醫）與六秀方向的概念',
          '房屋坐向與居住者八字的配合',
          '室內佈局：廚房、臥室、書房的方位選擇',
          '居住位置、睡眠方向對人生軌跡的影響',
        ],
        order: 1,
      },
      {
        id: 'tj-ky-02',
        title: '陰宅風水',
        subtitle: '墓地選擇與立向',
        description: '講解墓地選址的巒頭理論與立向禁忌，強調八煞黃泉等絕對禁忌。',
        keyPoints: [
          '八煞黃泉：墳墓和陽宅立向的絕對禁忌',
          '天星四貴的概念與應用',
          '龍穴砂水的基本判斷',
          '城局與九星的配合',
        ],
        order: 2,
      },
      {
        id: 'tj-ky-03',
        title: '風水與命運',
        subtitle: '地理調整改善運勢',
        description: '倪師關於風水與命運關係的核心理論——人事努力+地理調整>先天命運。',
        keyPoints: [
          '2/3大於1/3理論：人事努力+地理=2/3，先天命運=1/3',
          '好的風水地方要有魚蝦龜（生氣充沛的標誌）',
          '來龍、朝山、砂勢的綜合判斷',
          '結合紫微斗數的田宅宮來看風水需求',
        ],
        order: 3,
      },
    ],
  },
  {
    id: 'tj-tuiming',
    category: 'tianji',
    name: '推命學',
    nameEn: 'Tui Ming Xue',
    subtitle: '河洛數理派 · 子平法',
    description: '以子平法排列的易經推命術，結合河洛數理派理論，是紫微斗數之外的另一套命學工具。',
    details: [
      '推命學在天紀中作為紫微斗數的補充命學工具出現。',
      '倪師介紹了兩種命學體系：一是子平法排列的八字推命術，二是紫微斗數用年支排盤的方式。',
      '河洛數理派注重數字與五行的對應關係，從數理角度分析命運軌跡。',
      '倪師建議學生應同時掌握多種命學工具，以便交叉驗證、提高準確度。',
    ],
    school: '河洛數理派',
    lessons: '天紀課程穿插講解',
    references: [
      '《子平真詮》',
      '《河洛數理》',
    ],
    keywords: ['推命', '八字', '子平法', '河洛數理', '四柱', '五行', '天干地支'],
    icon: '⊡',
    status: 'preview',
    order: 4,
    slug: 'tuiming',
    chapters: [
      {
        id: 'tj-tm-01',
        title: '四柱八字基礎',
        subtitle: '天干地支與五行',
        description: '子平法的基礎知識，包括天干地支的五行屬性、十神關係、大運流年的排列。',
        keyPoints: [
          '十天干與十二地支的五行屬性',
          '年柱、月柱、日柱、時柱的排列',
          '十神體系與六親關係',
          '大運排列與流年推演',
        ],
        order: 1,
      },
    ],
  },
  {
    id: 'tj-mianxiang',
    category: 'tianji',
    name: '面相學',
    nameEn: 'Mian Xiang Xue',
    subtitle: '五形論 · 命相同參',
    description: '面相學是天紀課程中輔助命理判斷的重要工具，倪師強調「命相同參會提高準確率」。',
    details: [
      '面相學以「五形論」為核心——木、火、土、金、水五種面相型別。',
      '倪師強調五形的「純正性」決定貴賤：越純正的面相型別越貴。',
      '特殊貴相的識別：「南人北相、北人南相」是貴相的重要標誌。',
      '面相不是孤立判斷，必須結合紫微斗數的命盤分析，做到「命相同參」。',
    ],
    school: '五形面相',
    lessons: '天紀課程穿插講解',
    references: [
      '《麻衣相法》',
      '《神相全編》',
    ],
    keywords: ['面相', '五形論', '木火土金水', '命相同參', '南人北相', '氣色'],
    icon: '⊙',
    status: 'preview',
    order: 5,
    slug: 'mianxiang',
    chapters: [
      {
        id: 'tj-mx-01',
        title: '五形論基礎',
        subtitle: '木火土金水面相分類',
        description: '五種基本面相型別的特徵識別與貴賤判斷。',
        keyPoints: [
          '木形人：身材高瘦，面長色青',
          '火形人：面尖上闊，色紅氣急',
          '土形人：面圓肉厚，色黃聲重',
          '金形人：面方骨正，色白聲清',
          '水形人：面圓肉浮，色黑性柔',
        ],
        order: 1,
      },
    ],
  },
  {
    id: 'tj-cezi',
    category: 'tianji',
    name: '測字術',
    nameEn: 'Ce Zi Shu',
    subtitle: '拆字法 · 會意法',
    description: '測字是中國傳統占卜術之一，透過分析文字的筆畫、結構、含義來推斷吉凶。',
    details: [
      '測字術在天紀課程中作為輔助占卜手段出現。',
      '主要方法包括拆字法（分解字形）和會意法（聯想字義）。',
      '倪師認為測字的準確性取決於測者的悟性和經驗積累。',
    ],
    school: '傳統測字',
    lessons: '天紀課程穿插講解',
    references: [
      '《拆字辭典》',
    ],
    keywords: ['測字', '拆字法', '會意法', '占卜'],
    icon: '⊚',
    status: 'coming',
    order: 6,
    slug: 'cezi',
    chapters: [
      {
        id: 'tj-cz-01',
        title: '測字基礎',
        subtitle: '拆字與會意',
        description: '測字術的基本方法與實戰技巧。',
        keyPoints: [
          '拆字法：將文字拆解為偏旁部首分別解讀',
          '會意法：根據文字含義聯想推斷',
          '時間與環境因素的結合',
        ],
        order: 1,
      },
    ],
  },
];

// ─── 易經六十四卦資料庫 ──────────────────────────────────
export const HEXAGRAMS: Hexagram[] = [
  { number: 1, name: '乾', composition: '乾為天', upper: '乾', lower: '乾', meaning: '元亨利貞，天行健，君子以自強不息', niInterpretation: '純陽之卦，剛健中正，至大至剛', divination: '大吉大利，但需注意亢龍有悔' },
  { number: 2, name: '坤', composition: '坤為地', upper: '坤', lower: '坤', meaning: '元亨，利牝馬之貞，地勢坤，君子以厚德載物', niInterpretation: '純陰之卦，柔順承載', divination: '宜順從，不宜主動' },
  { number: 3, name: '屯', composition: '水雷屯', upper: '坎', lower: '震', meaning: '元亨利貞，勿用有攸往', niInterpretation: '萬物初生之象，創業維艱', divination: '初創時期，宜守不宜進' },
  { number: 4, name: '蒙', composition: '山水蒙', upper: '艮', lower: '坎', meaning: '亨，匪我求童蒙，童蒙求我', niInterpretation: '啟蒙教育之卦，需有耐心', divination: '求學問道有利，需虛心受教' },
  { number: 5, name: '需', composition: '水天需', upper: '坎', lower: '乾', meaning: '有孚，光亨貞吉，利涉大川', niInterpretation: '等待時機之卦，需要耐心', divination: '宜等待時機成熟再行動' },
  { number: 6, name: '訟', composition: '天水訟', upper: '乾', lower: '坎', meaning: '有孚窒惕，中吉終兇', niInterpretation: '爭訟之卦，不宜爭鬥', divination: '爭訟不利，宜和解退讓' },
  { number: 7, name: '師', composition: '地水師', upper: '坤', lower: '坎', meaning: '貞丈人吉，無咎', niInterpretation: '統兵之卦，需正義之師', divination: '行事需有正當名分' },
  { number: 8, name: '比', composition: '水地比', upper: '坎', lower: '坤', meaning: '吉，原筮元永貞，無咎', niInterpretation: '親附比輔之卦，團結互助', divination: '宜尋求合作與結盟' },
  { number: 9, name: '小畜', composition: '風天小畜', upper: '巽', lower: '乾', meaning: '亨，密雲不雨，自我西郊', niInterpretation: '小有積蓄之卦，力量不足以大成', divination: '小事可成，大事尚需等待' },
  { number: 10, name: '履', composition: '天澤履', upper: '乾', lower: '兌', meaning: '履虎尾，不咥人，亨', niInterpretation: '行事謹慎之卦，如履虎尾', divination: '小心謹慎可化險為夷' },
  { number: 11, name: '泰', composition: '地天泰', upper: '坤', lower: '乾', meaning: '小往大來，吉亨', niInterpretation: '天地交泰，通達之象', divination: '萬事亨通，大吉' },
  { number: 12, name: '否', composition: '天地否', upper: '乾', lower: '坤', meaning: '否之匪人，不利君子貞', niInterpretation: '天地不交，閉塞之象', divination: '諸事不順，宜守待時' },
  { number: 13, name: '同人', composition: '天火同人', upper: '乾', lower: '離', meaning: '同人於野，亨，利涉大川', niInterpretation: '志同道合之卦', divination: '合作共事有利' },
  { number: 14, name: '大有', composition: '火天大有', upper: '離', lower: '乾', meaning: '元亨', niInterpretation: '大豐收之卦，光明正大', divination: '事業豐盛，大有所獲' },
  { number: 15, name: '謙', composition: '地山謙', upper: '坤', lower: '艮', meaning: '亨，君子有終', niInterpretation: '謙遜之卦，唯一六爻皆吉之卦', divination: '謙虛謹慎，諸事吉利' },
  { number: 16, name: '豫', composition: '雷地豫', upper: '震', lower: '坤', meaning: '利建侯行師', niInterpretation: '安樂和豫之卦，但不可過度', divination: '可有所作為，但勿過於安逸' },
  { number: 17, name: '隨', composition: '澤雷隨', upper: '兌', lower: '震', meaning: '元亨利貞，無咎', niInterpretation: '隨順之卦，擇善而從', divination: '隨機應變，順勢而行' },
  { number: 18, name: '蠱', composition: '山風蠱', upper: '艮', lower: '巽', meaning: '元亨，利涉大川', niInterpretation: '整治積弊之卦，撥亂反正', divination: '需要整頓改革' },
  { number: 19, name: '臨', composition: '地澤臨', upper: '坤', lower: '兌', meaning: '元亨利貞，至於八月有兇', niInterpretation: '親臨監督之卦，居高臨下', divination: '可有所作為，但注意時效' },
  { number: 20, name: '觀', composition: '風地觀', upper: '巽', lower: '坤', meaning: '盥而不薦，有孚顒若', niInterpretation: '觀察審視之卦，以下觀上', divination: '宜觀察形勢，不宜冒進' },
  { number: 21, name: '噬嗑', composition: '火雷噬嗑', upper: '離', lower: '震', meaning: '亨，利用獄', niInterpretation: '刑罰決斷之卦，去除障礙', divination: '果斷處理障礙，排除困難' },
  { number: 22, name: '賁', composition: '山火賁', upper: '艮', lower: '離', meaning: '亨，小利有攸往', niInterpretation: '文飾之卦，外在修飾', divination: '注重外表形式，小事可成' },
  { number: 23, name: '剝', composition: '山地剝', upper: '艮', lower: '坤', meaning: '不利有攸往', niInterpretation: '剝落衰敗之卦', divination: '不宜行動，宜守靜待變' },
  { number: 24, name: '復', composition: '地雷復', upper: '坤', lower: '震', meaning: '亨，出入無疾，朋來無咎', niInterpretation: '一陽來複之卦，否極泰來', divination: '轉機出現，漸入佳境' },
  { number: 25, name: '無妄', composition: '天雷無妄', upper: '乾', lower: '震', meaning: '元亨利貞', niInterpretation: '無妄之災亦需坦然面對', divination: '正道而行可吉，妄動則兇' },
  { number: 26, name: '大畜', composition: '山天大畜', upper: '艮', lower: '乾', meaning: '利貞，不家食吉，利涉大川', niInterpretation: '大有積蓄之卦，厚積薄發', divination: '積累實力，蓄勢待發' },
  { number: 27, name: '頤', composition: '山雷頤', upper: '艮', lower: '震', meaning: '貞吉，觀頤，自求口實', niInterpretation: '養生頤養之卦', divination: '注意飲食養生，自力更生' },
  { number: 28, name: '大過', composition: '澤風大過', upper: '兌', lower: '巽', meaning: '棟橈，利有攸往，亨', niInterpretation: '陽氣過盛之卦，過猶不及', divination: '事情過度，需要調整' },
  { number: 29, name: '坎', composition: '坎為水', upper: '坎', lower: '坎', meaning: '習坎，有孚，維心亨', niInterpretation: '重重險難之卦，但心誠可亨', divination: '困難重重，但堅守信念可過關' },
  { number: 30, name: '離', composition: '離為火', upper: '離', lower: '離', meaning: '利貞，亨，畜牝牛吉', niInterpretation: '光明附麗之卦，文明之象', divination: '宜守正道，光明正大' },
  { number: 31, name: '鹹', composition: '澤山鹹', upper: '兌', lower: '艮', meaning: '亨利貞，取女吉', niInterpretation: '感應之卦，男女相感', divination: '感情婚姻大吉' },
  { number: 32, name: '恆', composition: '雷風恆', upper: '震', lower: '巽', meaning: '亨，無咎利貞，利有攸往', niInterpretation: '恆久不變之卦，持之以恆', divination: '堅持不懈可成功' },
  { number: 33, name: '遁', composition: '天山遁', upper: '乾', lower: '艮', meaning: '亨，小利貞', niInterpretation: '退隱之卦，適時退避', divination: '宜退不宜進，暫避鋒芒' },
  { number: 34, name: '大壯', composition: '雷天大壯', upper: '震', lower: '乾', meaning: '利貞', niInterpretation: '剛強壯盛之卦，但壯不可妄動', divination: '力量充沛，但需守正' },
  { number: 35, name: '晉', composition: '火地晉', upper: '離', lower: '坤', meaning: '康侯用錫馬蕃庶', niInterpretation: '日出地上之卦，步步高昇', divination: '事業晉升，前途光明' },
  { number: 36, name: '明夷', composition: '地火明夷', upper: '坤', lower: '離', meaning: '利艱貞', niInterpretation: '光明損傷之卦，韜光養晦', divination: '宜隱藏光芒，低調行事' },
  { number: 37, name: '家人', composition: '風火家人', upper: '巽', lower: '離', meaning: '利女貞', niInterpretation: '家庭和睦之卦', divination: '家庭事務吉利' },
  { number: 38, name: '睽', composition: '火澤睽', upper: '離', lower: '兌', meaning: '小事吉', niInterpretation: '背離分歧之卦，求同存異', divination: '小事可成，大事不宜' },
  { number: 39, name: '蹇', composition: '水山蹇', upper: '坎', lower: '艮', meaning: '利西南，不利東北', niInterpretation: '行路艱難之卦', divination: '前路困難，宜結伴同行' },
  { number: 40, name: '解', composition: '雷水解', upper: '震', lower: '坎', meaning: '利西南，無所往', niInterpretation: '解除困難之卦，雨過天晴', divination: '困難解除，宜速行事' },
  { number: 41, name: '損', composition: '山澤損', upper: '艮', lower: '兌', meaning: '有孚，元吉，無咎', niInterpretation: '損下益上之卦，適當犧牲', divination: '有所舍才有所得' },
  { number: 42, name: '益', composition: '風雷益', upper: '巽', lower: '震', meaning: '利有攸往，利涉大川', niInterpretation: '損上益下之卦，有利可圖', divination: '事業有益，宜大膽行動' },
  { number: 43, name: '夬', composition: '澤天夬', upper: '兌', lower: '乾', meaning: '揚於王庭', niInterpretation: '決斷之卦，以陽決陰', divination: '需果斷處理，不可猶豫' },
  { number: 44, name: '姤', composition: '天風姤', upper: '乾', lower: '巽', meaning: '女壯，勿用取女', niInterpretation: '相遇之卦，一陰初生', divination: '偶然相遇，不宜深交' },
  { number: 45, name: '萃', composition: '澤地萃', upper: '兌', lower: '坤', meaning: '亨，王假有廟', niInterpretation: '聚集之卦，眾志成城', divination: '聚集力量，團結協作' },
  { number: 46, name: '升', composition: '地風升', upper: '坤', lower: '巽', meaning: '元亨，用見大人', niInterpretation: '上升之卦，步步高昇', divination: '事業上升，宜見貴人' },
  { number: 47, name: '困', composition: '澤水困', upper: '兌', lower: '坎', meaning: '亨貞，大人吉，無咎', niInterpretation: '困頓之卦，但大人可吉', divination: '身處困境，守正可渡' },
  { number: 48, name: '井', composition: '水風井', upper: '坎', lower: '巽', meaning: '改邑不改井', niInterpretation: '水井之卦，不變中的恆常', divination: '固守根本，不可輕易改變' },
  { number: 49, name: '革', composition: '澤火革', upper: '兌', lower: '離', meaning: '己日乃孚', niInterpretation: '變革之卦，革故鼎新', divination: '時機成熟可變革' },
  { number: 50, name: '鼎', composition: '火風鼎', upper: '離', lower: '巽', meaning: '元吉，亨', niInterpretation: '鼎新之卦，建立新制', divination: '事業更新，大吉' },
  { number: 51, name: '震', composition: '震為雷', upper: '震', lower: '震', meaning: '亨，震來虩虩', niInterpretation: '震動之卦，初驚後安', divination: '先有驚擾，後可安定' },
  { number: 52, name: '艮', composition: '艮為山', upper: '艮', lower: '艮', meaning: '艮其背，不獲其身', niInterpretation: '止靜之卦，適可而止', divination: '宜停止觀望，不宜冒進' },
  { number: 53, name: '漸', composition: '風山漸', upper: '巽', lower: '艮', meaning: '女歸吉，利貞', niInterpretation: '循序漸進之卦', divination: '宜循序漸進，不可操之過急' },
  { number: 54, name: '歸妹', composition: '雷澤歸妹', upper: '震', lower: '兌', meaning: '徵兇，無攸利', niInterpretation: '少女出嫁之卦，位置不正', divination: '感情事宜需謹慎' },
  { number: 55, name: '豐', composition: '雷火豐', upper: '震', lower: '離', meaning: '亨，王假之', niInterpretation: '豐盛之卦，日中則昃', divination: '盛極必衰，宜居安思危' },
  { number: 56, name: '旅', composition: '火山旅', upper: '離', lower: '艮', meaning: '小亨，旅貞吉', niInterpretation: '旅行在外之卦', divination: '旅行出行小吉，需謹慎' },
  { number: 57, name: '巽', composition: '巽為風', upper: '巽', lower: '巽', meaning: '小亨，利有攸往', niInterpretation: '順從之卦，柔順滲透', divination: '宜順勢而為，不宜強行' },
  { number: 58, name: '兌', composition: '兌為澤', upper: '兌', lower: '兌', meaning: '亨利貞', niInterpretation: '喜悅之卦，和悅相處', divination: '和樂融融，社交有利' },
  { number: 59, name: '渙', composition: '風水渙', upper: '巽', lower: '坎', meaning: '亨，王假有廟', niInterpretation: '渙散之卦，化解分散', divination: '團隊渙散，需凝聚人心' },
  { number: 60, name: '節', composition: '水澤節', upper: '坎', lower: '兌', meaning: '亨，苦節不可貞', niInterpretation: '節制之卦，適度為宜', divination: '凡事需節制，過猶不及' },
  { number: 61, name: '中孚', composition: '風澤中孚', upper: '巽', lower: '兌', meaning: '豚魚吉，利涉大川', niInterpretation: '誠信之卦，至誠感通', divination: '誠信待人，可成大事' },
  { number: 62, name: '小過', composition: '雷山小過', upper: '震', lower: '艮', meaning: '亨利貞，可小事不可大事', niInterpretation: '小有過越之卦', divination: '小事可為，大事不宜' },
  { number: 63, name: '既濟', composition: '水火既濟', upper: '坎', lower: '離', meaning: '亨小，利貞，初吉終亂', niInterpretation: '事已成就之卦，但需謹防衰敗', divination: '事情已成，但需注意善後' },
  { number: 64, name: '未濟', composition: '火水未濟', upper: '離', lower: '坎', meaning: '亨，小狐汔濟，濡其尾', niInterpretation: '尚未完成之卦，事在人為', divination: '事未完成，需繼續努力' },
];

// ─── 堪輿學條目 ──────────────────────────────────────────
export const FENGSHUI_ENTRIES: FengShuiEntry[] = [
  {
    id: 'fs-bashayq',
    title: '八煞黃泉',
    category: 'theory',
    description: '立向的絕對禁忌，墳墓和陽宅都不可犯。八煞黃泉是風水學中最嚴重的忌諱之一。',
    keyPoints: ['墳墓和陽宅立向使用', '絕對不能立的向', '犯之主大凶'],
  },
  {
    id: 'fs-sanjilx',
    title: '三吉六秀',
    category: 'yangzhai',
    description: '陽宅風水中的吉利方位。三吉方向（生氣、延年、天醫）代表最佳的方位選擇。',
    keyPoints: ['三吉：生氣、延年、天醫', '六秀方向有好的砂勢則吉', '有山勢、來龍、朝山為佳'],
  },
  {
    id: 'fs-tianxsg',
    title: '天星四貴',
    category: 'yinzhai',
    description: '陰宅選址的高階技法，用於判斷墓地周圍的貴氣方位。',
    keyPoints: ['天星方位判斷貴氣', '與龍穴砂水配合使用', '九星派核心理論之一'],
  },
  {
    id: 'fs-yangzhai',
    title: '陽宅佈局',
    category: 'yangzhai',
    description: '居住環境的風水佈局原則，包括房屋坐向、室內格局、周圍環境的綜合考量。',
    keyPoints: ['房屋坐向需配合居住者', '廚房方位影響家人健康', '臥室位置影響夫妻感情', '居住位置與睡眠方向影響運勢'],
  },
  {
    id: 'fs-longxueshashui',
    title: '龍穴砂水',
    category: 'yinzhai',
    description: '風水四大要素——龍脈走勢、穴位選擇、砂的環抱、水的流向，構成完整的風水格局。',
    keyPoints: ['龍：山脈走勢與來龍', '穴：藏風聚氣的最佳位置', '砂：穴位周圍的山勢環抱', '水：水流走向與聚散'],
  },
  {
    id: 'fs-chengjujiuxing',
    title: '城局與九星',
    category: 'theory',
    description: '楊救貧九星派的核心理論，透過九星的排列組合判斷風水格局的吉凶。',
    keyPoints: ['九星：貪巨祿文廉武破左右', '城局形勢的整體判斷', '與天星四貴配合使用'],
  },
];

// ─── 天紀24集課程結構（每集2小時：前半段命學/後半段易經） ──
export const TIANJI_EPISODES: TianjiEpisode[] = [
  { dvd: 1, firstHalf: '天紀開篇·天紀與真理', secondHalf: '易經三義·先後天八卦', highlights: ['如何分辨君子與小人', '天地人三才論', '紫微斗數為何優於子平法', '文字只是船真理才是彼岸'] },
  { dvd: 2, firstHalf: '紫微斗數·十二宮位詳解', secondHalf: '八卦地理配置·爻變與時機', highlights: ['命宮為本三方為用', '夫妻宮兼看福德宮', '面相五形論', '名位相等原則', '卜筮有時機不疑何卜'] },
  { dvd: 3, firstHalf: '紫微斗數·星辰介紹(上)', secondHalf: '乾坤屯蒙需訟', highlights: ['紫微星帝座特質', '天府財庫星', '太陽星廟旺利陷', '天機善星智慧'] },
  { dvd: 4, firstHalf: '紫微斗數·星辰介紹(下)', secondHalf: '師比小畜履泰否', highlights: ['殺破狼三星一定同在三方', '武曲財星', '貪狼桃花星', '廉貞囚星', '巨門暗星'] },
  { dvd: 5, firstHalf: '紫微斗數·十二張案例講義', secondHalf: '同人大有謙豫隨蠱', highlights: ['十二張案例紫微在十二宮各一張', '命宮貪狼文武雙全', '身宮在財帛宮為職業婦女', '陽宅化解論'] },
  { dvd: 6, firstHalf: '紫微斗數·四化星詳解', secondHalf: '臨觀噬嗑賁剝復', highlights: ['化祿主財性守', '化權性剛代表官印', '化科主科名名氣', '化忌主劫殺', '大限流年四化疊加'] },
  { dvd: 7, firstHalf: '紫微斗數·格局論(上)', secondHalf: '無妄大畜頤大過坎離', highlights: ['殺破狼格局變動開創', '火貪格主暴發', '三方四正看格局', '官祿宮最喜權星'] },
  { dvd: 8, firstHalf: '紫微斗數·格局論(下)', secondHalf: '鹹恆遁大壯晉明夷', highlights: ['流年批命法', '迷津評斷一生總格局', '命相同參提高準確率', '南人北相為貴相'] },
  { dvd: 9, firstHalf: '紫微斗數·大限流年', secondHalf: '家人睽蹇解損益', highlights: ['大限十年運勢', '小限流年推算', '人定勝天論', '三年前化解論'] },
  { dvd: 10, firstHalf: '紫微斗數·實戰案例(上)', secondHalf: '夬姤萃升困井', highlights: ['官祿化忌事業受阻', '財帛化祿財運亨通', '夫妻宮煞星婚姻不順'] },
  { dvd: 11, firstHalf: '紫微斗數·實戰案例(下)', secondHalf: '革鼎震艮漸歸妹', highlights: ['疾厄宮判斷健康', '結合中醫子午流注', '煞星在午主心臟在醜主肝'] },
  { dvd: 12, firstHalf: '面相學·五形論詳解', secondHalf: '豐旅巽兌渙節', highlights: ['木火土金水五種面相型別', '越純越貴原則', '氣色主兩個禮拜', '眼神判斷法'] },
  { dvd: 13, firstHalf: '面相學·氣色與斷命', secondHalf: '中孚小過既濟未濟', highlights: ['面相氣色判斷吉凶', '印堂日角月角', '眉毛代表六親', '眼袋判斷子女'] },
  { dvd: 14, firstHalf: '推命學·子平法入門', secondHalf: '64卦綜合應用(上)', highlights: ['子平法四柱八字排列', '天干地支五行屬性', '十神體系'] },
  { dvd: 15, firstHalf: '推命學·大運流年', secondHalf: '64卦綜合應用(下)', highlights: ['大運排列', '流年推演', '卦象在實際生活中的應用'] },
  { dvd: 16, firstHalf: '測字術·拆字會意法', secondHalf: '占卜實戰·起卦法', highlights: ['拆字法分解偏旁', '會意法聯想推斷', '揲蓍法', '金錢卦'] },
  { dvd: 17, firstHalf: '測字術·實戰案例', secondHalf: '六爻斷事技巧', highlights: ['測字時機和環境', '六神占斷', '用神取用'] },
  { dvd: 18, firstHalf: '堪輿學·巒頭論(上)', secondHalf: '龍穴砂水基礎', highlights: ['山形水勢判斷', '龍脈走勢與氣脈', '穴位藏風聚氣'] },
  { dvd: 19, firstHalf: '堪輿學·巒頭論(下)', secondHalf: '羅盤使用與理氣', highlights: ['砂手環抱', '水口進出', '羅盤方位測量', '九星飛布原理'] },
  { dvd: 20, firstHalf: '堪輿學·陽宅風水', secondHalf: '三吉六秀·天星四貴', highlights: ['房屋坐向選擇', '室內方位安排', '三吉方向', '六秀方向好砂則吉'] },
  { dvd: 21, firstHalf: '堪輿學·陰宅風水', secondHalf: '八煞黃泉·城局九星', highlights: ['八煞黃泉絕對禁忌', '天星四貴', '城局形勢判斷', '來龍朝山砂勢'] },
  { dvd: 22, firstHalf: '堪輿學·2/3大於1/3', secondHalf: '風水改運例項', highlights: ['人事+地理=2/3>天命1/3', '好風水有魚蝦龜', '床位朝向決定生子性別'] },
  { dvd: 23, firstHalf: '綜合應用·命相卜術結合', secondHalf: '天紀在生活中的實踐', highlights: ['紫微+面相+易經綜合判斷', '天地人三紀統一觀', '倪師批命實戰示範'] },
  { dvd: 24, firstHalf: '天紀總結·核心心法', secondHalf: '傳承與期許', highlights: ['天紀精神總結', '命運掌握在自己手上', '文化傳承使命', '不希望中華文化失傳'] },
];

// ─── 倪師天紀核心語錄庫 ──────────────────────────────────
export const TIANJI_QUOTES = [
  { text: '文字只是協助諸位到達真理的彼岸，千萬不要三個月以後，怎麼還是扛著船在馬路上跑', topic: '學習態度' },
  { text: '大道至簡——飛星飛來飛去太複雜，不搞這個', topic: '紫微斗數' },
  { text: '命宮為本，三方為用——命宮主星決定基本格局與天生性格，三方決定用武之地', topic: '紫微斗數' },
  { text: '身宮在財帛宮的女孩子，一般來說就是職業婦女', topic: '紫微斗數' },
  { text: '最怕的是七殺臨身，七殺臨身的人一輩子多敗少成', topic: '紫微斗數' },
  { text: '官祿宮最喜歡權星入進來', topic: '紫微斗數' },
  { text: '算命就是一個討論果的哲學', topic: '命學哲理' },
  { text: '命是天註定的，運掌握在我們自己手上', topic: '命學哲理' },
  { text: '三年前有辦法化解，到了時候再改都是事後。碗打破了我們再去解', topic: '命學哲理' },
  { text: '禍福無門，咎由自取', topic: '命學哲理' },
  { text: '看到外面，就知道里面藏了什麼', topic: '面相' },
  { text: '看相最難看的就是氣色。氣色主兩個禮拜', topic: '面相' },
  { text: '越純越貴——五形越純正的面相型別越貴', topic: '面相' },
  { text: '南人北相、北人南相是貴相的重要標誌', topic: '面相' },
  { text: '害的到你的叫做小人。會影響到你的叫做小人', topic: '識人' },
  { text: '眼珠閃動主心術不正，四白眼主橫死，三角眼主心生毒計', topic: '面相' },
  { text: '人事的努力加上地理上的調整，一定能大於先天的命運', topic: '堪輿' },
  { text: '好的風水地方要有魚蝦龜——生氣充沛的標誌', topic: '堪輿' },
  { text: '八煞黃泉是墳墓和陽宅立向的絕對禁忌', topic: '堪輿' },
  { text: '唯有紫微斗數可以把天文和地理兩個融合在一起', topic: '紫微斗數' },
  { text: '如果讀了易經，越弄越複雜，就是沒有讀通易經', topic: '易經' },
  { text: '不疑何卜——只有有疑慮時才占卜', topic: '易經' },
  { text: '外象一直在變，但精神是一樣的', topic: '易經' },
  { text: '爸爸住爸爸位置，兒子住兒子位置，叫做名位相等', topic: '堪輿' },
  { text: '中國五百年出一個天官，現在還不到五百年', topic: '天文' },
  { text: '煞星透過疾厄宮在午主心臟，在醜主肝', topic: '紫微斗數' },
  { text: '我不希望這些中華文化失傳，所以就教了許多學生', topic: '傳承' },
  { text: '命相同參會提高準確率', topic: '綜合' },
  { text: '天紀就是自然法則，是真理', topic: '天紀總論' },
];

// ─── 統計 ────────────────────────────────────────────────
export const TIANJI_STATS = {
  totalModules: TIANJI_MODULES.length,
  activeModules: TIANJI_MODULES.filter(m => m.status === 'active').length,
  totalChapters: TIANJI_MODULES.reduce((sum, m) => sum + m.chapters.length, 0),
  totalHexagrams: HEXAGRAMS.length,
  totalFengShui: FENGSHUI_ENTRIES.length,
  totalEpisodes: TIANJI_EPISODES.length,
  totalQuotes: 29,
  videoHours: 48,
  videoEpisodes: 24,
  hdEpisodes: 83,
  recordYear: 1994,
  lectureBooks: ['天機道', '人間道', '地脈道', '64卦易圖'],
  schools: ['三合派（紫微斗數）', '象數派（易經）', '九星派（堪輿）', '河洛數理派（推命）'],
};
